[{"title":"_Abs(PExpressionRec)","href":"ParseExpr._Abs.htm"}
,{"title":"_Add(PExpressionRec)","href":"ParseExpr._Add.htm"}
,{"title":"_Add1(PExpressionRec)","href":"ParseExpr._Add1.htm"}
,{"title":"_And(PExpressionRec)","href":"ParseExpr._And.htm"}
,{"title":"_ArcCos(PExpressionRec)","href":"ParseExpr._ArcCos.htm"}
,{"title":"_ArcCosh(PExpressionRec)","href":"ParseExpr._ArcCosh.htm"}
,{"title":"_ArcSin(PExpressionRec)","href":"ParseExpr._ArcSin.htm"}
,{"title":"_ArcSinh(PExpressionRec)","href":"ParseExpr._ArcSinh.htm"}
,{"title":"_arctan(PExpressionRec)","href":"ParseExpr._arctan.htm"}
,{"title":"_ArcTan2(PExpressionRec)","href":"ParseExpr._ArcTan2.htm"}
,{"title":"_ArcTanh(PExpressionRec)","href":"ParseExpr._ArcTanh.htm"}
,{"title":"_Assign(PExpressionRec)","href":"ParseExpr._Assign.htm"}
,{"title":"_Cos(PExpressionRec)","href":"ParseExpr._Cos.htm"}
,{"title":"_Cosh(PExpressionRec)","href":"ParseExpr._Cosh.htm"}
,{"title":"_DegToRad(PExpressionRec)","href":"ParseExpr._DegToRad.htm"}
,{"title":"_Div(PExpressionRec)","href":"ParseExpr._Div.htm"}
,{"title":"_eq(PExpressionRec)","href":"ParseExpr._eq.htm"}
,{"title":"_exp(PExpressionRec)","href":"ParseExpr._exp.htm"}
,{"title":"_factorial(PExpressionRec)","href":"ParseExpr._factorial.htm"}
,{"title":"_ge(PExpressionRec)","href":"ParseExpr._ge.htm"}
,{"title":"_gt(PExpressionRec)","href":"ParseExpr._gt.htm"}
,{"title":"_if(PExpressionRec)","href":"ParseExpr._if.htm"}
,{"title":"_IntPower(PExpressionRec)","href":"ParseExpr._IntPower.htm"}
,{"title":"_isNaN(PExpressionRec)","href":"ParseExpr._isNaN.htm"}
,{"title":"_le(PExpressionRec)","href":"ParseExpr._le.htm"}
,{"title":"_ln(PExpressionRec)","href":"ParseExpr._ln.htm"}
,{"title":"_log10(PExpressionRec)","href":"ParseExpr._log10.htm"}
,{"title":"_logN(PExpressionRec)","href":"ParseExpr._logN.htm"}
,{"title":"_lt(PExpressionRec)","href":"ParseExpr._lt.htm"}
,{"title":"_max(PExpressionRec)","href":"ParseExpr._max.htm"}
,{"title":"_min(PExpressionRec)","href":"ParseExpr._min.htm"}
,{"title":"_minus(PExpressionRec)","href":"ParseExpr._minus.htm"}
,{"title":"_minus1(PExpressionRec)","href":"ParseExpr._minus1.htm"}
,{"title":"_mod(PExpressionRec)","href":"ParseExpr._mod.htm"}
,{"title":"_mult(PExpressionRec)","href":"ParseExpr._mult.htm"}
,{"title":"_ne(PExpressionRec)","href":"ParseExpr._ne.htm"}
,{"title":"_negate(PExpressionRec)","href":"ParseExpr._negate.htm"}
,{"title":"_not(PExpressionRec)","href":"ParseExpr._not.htm"}
,{"title":"_or(PExpressionRec)","href":"ParseExpr._or.htm"}
,{"title":"_Percentage(PExpressionRec)","href":"ParseExpr._Percentage.htm"}
,{"title":"_plus(PExpressionRec)","href":"ParseExpr._plus.htm"}
,{"title":"_Pos(string,string)","href":"ParseExpr._Pos.htm"}
,{"title":"_Power(PExpressionRec)","href":"ParseExpr._Power.htm"}
,{"title":"_RadToDeg(PExpressionRec)","href":"ParseExpr._RadToDeg.htm"}
,{"title":"_randG(PExpressionRec)","href":"ParseExpr._randG.htm"}
,{"title":"_random(PExpressionRec)","href":"ParseExpr._random.htm"}
,{"title":"_realDivide(PExpressionRec)","href":"ParseExpr._realDivide.htm"}
,{"title":"_round(PExpressionRec)","href":"ParseExpr._round.htm"}
,{"title":"_sin(PExpressionRec)","href":"ParseExpr._sin.htm"}
,{"title":"_Sinh(PExpressionRec)","href":"ParseExpr._Sinh.htm"}
,{"title":"_sqr(PExpressionRec)","href":"ParseExpr._sqr.htm"}
,{"title":"_sqrt(PExpressionRec)","href":"ParseExpr._sqrt.htm"}
,{"title":"_StrEq(string,string)","href":"ParseClass._StrEq.htm"}
,{"title":"_StrGe(string,string)","href":"ParseClass._StrGe.htm"}
,{"title":"_StrGt(string,string)","href":"ParseClass._StrGt.htm"}
,{"title":"_StrIn(string,string)","href":"ParseClass._StrIn.htm"}
,{"title":"_StringFunc(PExpressionRec)","href":"ParseClass._StringFunc.htm"}
,{"title":"_StrInt(string,string)","href":"ParseClass._StrInt.htm"}
,{"title":"_Strle(string,string)","href":"ParseClass._Strle.htm"}
,{"title":"_Strlt(string,string)","href":"ParseClass._Strlt.htm"}
,{"title":"_Strne(string,string)","href":"ParseClass._Strne.htm"}
,{"title":"_tan(PExpressionRec)","href":"ParseExpr._tan.htm"}
,{"title":"_tanh(PExpressionRec)","href":"ParseExpr._tanh.htm"}
,{"title":"_trunc(PExpressionRec)","href":"ParseExpr._trunc.htm"}
,{"title":"_Variable(PExpressionRec)","href":"ParseClass._Variable.htm"}
,{"title":"_xor(PExpressionRec)","href":"ParseExpr._xor.htm"}
,{"title":"addAssertion(THeaderNode,string)","href":"Casbin.Parser.AST.addAssertion.htm"}
,{"title":"AssignmentCharForConfig","href":"Casbin.Core.Defaults.AssignmentCharForConfig.htm"}
,{"title":"AssignmentCharForModel","href":"Casbin.Core.Defaults.AssignmentCharForModel.htm"}
,{"title":"AssignmentCharForPolicies","href":"Casbin.Core.Defaults.AssignmentCharForPolicies.htm"}
,{"title":"Casbin.Adapter.Base","href":"Casbin.Adapter.Base.htm"}
,{"title":"Casbin.Adapter.Base.TBaseAdapter","href":"Casbin.Adapter.Base.TBaseAdapter.htm"}
,{"title":"Casbin.Adapter.Filesystem","href":"Casbin.Adapter.Filesystem.htm"}
,{"title":"Casbin.Adapter.Filesystem.Policy","href":"Casbin.Adapter.Filesystem.Policy.htm"}
,{"title":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.htm"}
,{"title":"Casbin.Adapter.Filesystem.TFileAdapter","href":"Casbin.Adapter.Filesystem.TFileAdapter.htm"}
,{"title":"Casbin.Adapter.Policy.Types","href":"Casbin.Adapter.Policy.Types.htm"}
,{"title":"Casbin.Adapter.Policy.Types.IPolicyAdapter","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.htm"}
,{"title":"Casbin.Adapter.Types","href":"Casbin.Adapter.Types.htm"}
,{"title":"Casbin.Adapter.Types.IAdapter","href":"Casbin.Adapter.Types.IAdapter.htm"}
,{"title":"Casbin.Core.Base.Types","href":"Casbin.Core.Base.Types.htm"}
,{"title":"Casbin.Core.Base.Types.IBaseInterface","href":"Casbin.Core.Base.Types.IBaseInterface.htm"}
,{"title":"Casbin.Core.Base.Types.TBaseInterfacedObject","href":"Casbin.Core.Base.Types.TBaseInterfacedObject.htm"}
,{"title":"Casbin.Core.Base.Types.TBaseObject","href":"Casbin.Core.Base.Types.TBaseObject.htm"}
,{"title":"Casbin.Core.Base.Types.TFilterArray","href":"Casbin.Core.Base.Types.TFilterArray.htm"}
,{"title":"Casbin.Core.Defaults","href":"Casbin.Core.Defaults.htm"}
,{"title":"Casbin.Core.Logger.Base","href":"Casbin.Core.Logger.Base.htm"}
,{"title":"Casbin.Core.Logger.Base.TBaseLogger","href":"Casbin.Core.Logger.Base.TBaseLogger.htm"}
,{"title":"Casbin.Core.Logger.Default","href":"Casbin.Core.Logger.Default.htm"}
,{"title":"Casbin.Core.Logger.Default.TDefaultLogger","href":"Casbin.Core.Logger.Default.TDefaultLogger.htm"}
,{"title":"Casbin.Core.Logger.Types","href":"Casbin.Core.Logger.Types.htm"}
,{"title":"Casbin.Core.Logger.Types.ILogger","href":"Casbin.Core.Logger.Types.ILogger.htm"}
,{"title":"Casbin.Core.Strings","href":"Casbin.Core.Strings.htm"}
,{"title":"Casbin.Core.Utilities","href":"Casbin.Core.Utilities.htm"}
,{"title":"Casbin.Effect","href":"Casbin.Effect.htm"}
,{"title":"Casbin.Effect.Types","href":"Casbin.Effect.Types.htm"}
,{"title":"Casbin.Effect.Types.TEffectArray","href":"Casbin.Effect.Types.TEffectArray.htm"}
,{"title":"Casbin.Effect.Types.TEffectCondition","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"Casbin.Effect.Types.TEffectResult","href":"Casbin.Effect.Types.TEffectResult.htm"}
,{"title":"Casbin.Exception.Types","href":"Casbin.Exception.Types.htm"}
,{"title":"Casbin.Exception.Types.ECasbinException","href":"Casbin.Exception.Types.ECasbinException.htm"}
,{"title":"Casbin.Functions","href":"Casbin.Functions.htm"}
,{"title":"Casbin.Functions.TFunctions","href":"Casbin.Functions.TFunctions.htm"}
,{"title":"Casbin.Functions.Types","href":"Casbin.Functions.Types.htm"}
,{"title":"Casbin.Functions.Types.IFunctions","href":"Casbin.Functions.Types.IFunctions.htm"}
,{"title":"Casbin.Functions.Types.TCasbinFunc","href":"Casbin.Functions.Types.TCasbinFunc.htm"}
,{"title":"Casbin.Matcher","href":"Casbin.Matcher.htm"}
,{"title":"Casbin.Matcher.TMatcher","href":"Casbin.Matcher.TMatcher.htm"}
,{"title":"Casbin.Matcher.Types","href":"Casbin.Matcher.Types.htm"}
,{"title":"Casbin.Matcher.Types.IMatcher","href":"Casbin.Matcher.Types.IMatcher.htm"}
,{"title":"Casbin.Model","href":"Casbin.Model.htm"}
,{"title":"Casbin.Model.Sections.Default","href":"Casbin.Model.Sections.Default.htm"}
,{"title":"Casbin.Model.Sections.Default.TSectionDefault","href":"Casbin.Model.Sections.Default.TSectionDefault.htm"}
,{"title":"Casbin.Model.Sections.Types","href":"Casbin.Model.Sections.Types.htm"}
,{"title":"Casbin.Model.Sections.Types.TSection","href":"Casbin.Model.Sections.Types.TSection.htm"}
,{"title":"Casbin.Model.Sections.Types.TSectionType","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"Casbin.Model.Sections.Types.TSectionTypeSet","href":"Casbin.Model.Sections.Types.TSectionTypeSet.htm"}
,{"title":"Casbin.Model.TModel","href":"Casbin.Model.TModel.htm"}
,{"title":"Casbin.Model.Types","href":"Casbin.Model.Types.htm"}
,{"title":"Casbin.Model.Types.IModel","href":"Casbin.Model.Types.IModel.htm"}
,{"title":"Casbin.Parser","href":"Casbin.Parser.htm"}
,{"title":"Casbin.Parser.AST","href":"Casbin.Parser.AST.htm"}
,{"title":"Casbin.Parser.AST.Types","href":"Casbin.Parser.AST.Types.htm"}
,{"title":"Casbin.Parser.AST.Types.TAssertionNode","href":"Casbin.Parser.AST.Types.TAssertionNode.htm"}
,{"title":"Casbin.Parser.AST.Types.TBaseNode","href":"Casbin.Parser.AST.Types.TBaseNode.htm"}
,{"title":"Casbin.Parser.AST.Types.TChildNode","href":"Casbin.Parser.AST.Types.TChildNode.htm"}
,{"title":"Casbin.Parser.AST.Types.TEffectNode","href":"Casbin.Parser.AST.Types.TEffectNode.htm"}
,{"title":"Casbin.Parser.AST.Types.THeaderNode","href":"Casbin.Parser.AST.Types.THeaderNode.htm"}
,{"title":"Casbin.Parser.AST.Types.TNodeCollection","href":"Casbin.Parser.AST.Types.TNodeCollection.htm"}
,{"title":"Casbin.Parser.TParser","href":"Casbin.Parser.TParser.htm"}
,{"title":"Casbin.Parser.Types","href":"Casbin.Parser.Types.htm"}
,{"title":"Casbin.Parser.Types.IParser","href":"Casbin.Parser.Types.IParser.htm"}
,{"title":"Casbin.Parser.Types.TParserStatus","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"Casbin.Parser.Types.TParseType","href":"Casbin.Parser.Types.TParseType.htm"}
,{"title":"Casbin.Policy","href":"Casbin.Policy.htm"}
,{"title":"Casbin.Policy.TPolicyManager","href":"Casbin.Policy.TPolicyManager.htm"}
,{"title":"Casbin.Policy.Types","href":"Casbin.Policy.Types.htm"}
,{"title":"Casbin.Policy.Types.IPolicyManager","href":"Casbin.Policy.Types.IPolicyManager.htm"}
,{"title":"CasbinD103Rio","href":"CasbinD103Rio.htm"}
,{"title":"configFileString","href":"Casbin.Core.Strings.configFileString.htm"}
,{"title":"congigSections","href":"Casbin.Model.Sections.Types.congigSections.htm"}
,{"title":"createDefaultSection(TSectionType)","href":"Casbin.Model.Sections.Default.createDefaultSection.htm"}
,{"title":"DefaultCacheSize","href":"Casbin.Adapter.Policy.Types.DefaultCacheSize.htm"}
,{"title":"DefaultCommentCharacters","href":"Casbin.Core.Defaults.DefaultCommentCharacters.htm"}
,{"title":"DefaultMultilineCharacters","href":"Casbin.Core.Defaults.DefaultMultilineCharacters.htm"}
,{"title":"defaultSection","href":"Casbin.Model.Sections.Default.defaultSection.htm"}
,{"title":"DefaultSection","href":"Casbin.Core.Defaults.DefaultSection.htm"}
,{"title":"ECasbinException","href":"Casbin.Exception.Types.ECasbinException.htm"}
,{"title":"effectConditions","href":"Casbin.Effect.Types.effectConditions.htm"}
,{"title":"EOL","href":"Casbin.Core.Defaults.EOL.htm"}
,{"title":"EParserException","href":"ParseClass.EParserException.htm"}
,{"title":"errorPrefix","href":"ParseExpr.errorPrefix.htm"}
,{"title":"errorSectionNotFound","href":"Casbin.Core.Strings.errorSectionNotFound.htm"}
,{"title":"errorUnknownAssertion","href":"Casbin.Core.Strings.errorUnknownAssertion.htm"}
,{"title":"errorWrongHeaderFormat","href":"Casbin.Core.Strings.errorWrongHeaderFormat.htm"}
,{"title":"findEndPos(string)","href":"Casbin.Core.Utilities.findEndPos.htm"}
,{"title":"findStartPos","href":"Casbin.Core.Utilities.findStartPos.htm"}
,{"title":"IAdapter","href":"Casbin.Adapter.Types.IAdapter.htm"}
,{"title":"IAdapter.Assertions","href":"Casbin.Adapter.Types.IAdapter.Assertions.htm"}
,{"title":"IAdapter.clear","href":"Casbin.Adapter.Types.IAdapter.clear.htm"}
,{"title":"IAdapter.Filter","href":"Casbin.Adapter.Types.IAdapter.Filter.htm"}
,{"title":"IAdapter.Filtered","href":"Casbin.Adapter.Types.IAdapter.Filtered.htm"}
,{"title":"IAdapter.getAssertions","href":"Casbin.Adapter.Types.IAdapter.getAssertions.htm"}
,{"title":"IAdapter.getFilter","href":"Casbin.Adapter.Types.IAdapter.getFilter.htm"}
,{"title":"IAdapter.getFiltered","href":"Casbin.Adapter.Types.IAdapter.getFiltered.htm"}
,{"title":"IAdapter.getLogger","href":"Casbin.Adapter.Types.IAdapter.getLogger.htm"}
,{"title":"IAdapter.load(TFilterArray)","href":"Casbin.Adapter.Types.IAdapter.load.htm"}
,{"title":"IAdapter.Logger","href":"Casbin.Adapter.Types.IAdapter.Logger.htm"}
,{"title":"IAdapter.save","href":"Casbin.Adapter.Types.IAdapter.save.htm"}
,{"title":"IAdapter.setAssertions(TList)","href":"Casbin.Adapter.Types.IAdapter.setAssertions.htm"}
,{"title":"IAdapter.setLogger(ILogger)","href":"Casbin.Adapter.Types.IAdapter.setLogger.htm"}
,{"title":"IAdapter.toOutputString","href":"Casbin.Adapter.Types.IAdapter.toOutputString.htm"}
,{"title":"IBaseInterface","href":"Casbin.Core.Base.Types.IBaseInterface.htm"}
,{"title":"IFunctions","href":"Casbin.Functions.Types.IFunctions.htm"}
,{"title":"IFunctions.list","href":"Casbin.Functions.Types.IFunctions.list.htm"}
,{"title":"IFunctions.refreshFunctions","href":"Casbin.Functions.Types.IFunctions.refreshFunctions.htm"}
,{"title":"IFunctions.registerFunction(string,TCasbinFunc)","href":"Casbin.Functions.Types.IFunctions.registerFunction.htm"}
,{"title":"IFunctions.retrieveFunction(string)","href":"Casbin.Functions.Types.IFunctions.retrieveFunction.htm"}
,{"title":"ILogger","href":"Casbin.Core.Logger.Types.ILogger.htm"}
,{"title":"ILogger.Enabled","href":"Casbin.Core.Logger.Types.ILogger.Enabled.htm"}
,{"title":"ILogger.getEnabled","href":"Casbin.Core.Logger.Types.ILogger.getEnabled.htm"}
,{"title":"ILogger.getLastLoggedMessage","href":"Casbin.Core.Logger.Types.ILogger.getLastLoggedMessage.htm"}
,{"title":"ILogger.LastLoggedMessage","href":"Casbin.Core.Logger.Types.ILogger.LastLoggedMessage.htm"}
,{"title":"ILogger.log(string)","href":"Casbin.Core.Logger.Types.ILogger.log.htm"}
,{"title":"ILogger.setEnabled(Boolean)","href":"Casbin.Core.Logger.Types.ILogger.setEnabled.htm"}
,{"title":"IMatcher","href":"Casbin.Matcher.Types.IMatcher.htm"}
,{"title":"IMatcher.evaluateMatcher(string)","href":"Casbin.Matcher.Types.IMatcher.evaluateMatcher.htm"}
,{"title":"IModel","href":"Casbin.Model.Types.IModel.htm"}
,{"title":"IModel.assertions(TSectionType)","href":"Casbin.Model.Types.IModel.assertions.htm"}
,{"title":"IModel.section(TSectionType,Boolean)","href":"Casbin.Model.Types.IModel.section.htm"}
,{"title":"IParser","href":"Casbin.Parser.Types.IParser.htm"}
,{"title":"IParser.ErrorMessage","href":"Casbin.Parser.Types.IParser.ErrorMessage.htm"}
,{"title":"IParser.getErrorMessage","href":"Casbin.Parser.Types.IParser.getErrorMessage.htm"}
,{"title":"IParser.getLogger","href":"Casbin.Parser.Types.IParser.getLogger.htm"}
,{"title":"IParser.getNodes","href":"Casbin.Parser.Types.IParser.getNodes.htm"}
,{"title":"IParser.getParseType","href":"Casbin.Parser.Types.IParser.getParseType.htm"}
,{"title":"IParser.getStatus","href":"Casbin.Parser.Types.IParser.getStatus.htm"}
,{"title":"IParser.Logger","href":"Casbin.Parser.Types.IParser.Logger.htm"}
,{"title":"IParser.Nodes","href":"Casbin.Parser.Types.IParser.Nodes.htm"}
,{"title":"IParser.parse","href":"Casbin.Parser.Types.IParser.parse.htm"}
,{"title":"IParser.ParseType","href":"Casbin.Parser.Types.IParser.ParseType.htm"}
,{"title":"IParser.setLogger(ILogger)","href":"Casbin.Parser.Types.IParser.setLogger.htm"}
,{"title":"IParser.Status","href":"Casbin.Parser.Types.IParser.Status.htm"}
,{"title":"IPolicyAdapter","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.htm"}
,{"title":"IPolicyAdapter.add(string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.add.htm"}
,{"title":"IPolicyAdapter.AutoSave","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.AutoSave.htm"}
,{"title":"IPolicyAdapter.Cached","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.Cached.htm"}
,{"title":"IPolicyAdapter.CacheSize","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.CacheSize.htm"}
,{"title":"IPolicyAdapter.getAutoSave","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getAutoSave.htm"}
,{"title":"IPolicyAdapter.getCached","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCached.htm"}
,{"title":"IPolicyAdapter.getCacheSize","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCacheSize.htm"}
,{"title":"IPolicyAdapter.remove(string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string).htm"}
,{"title":"IPolicyAdapter.remove(string,string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string,string).htm"}
,{"title":"IPolicyAdapter.setAutoSave(Boolean)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setAutoSave.htm"}
,{"title":"IPolicyAdapter.setCached(boolean)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCached.htm"}
,{"title":"IPolicyAdapter.setCacheSize(Integer)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCacheSize.htm"}
,{"title":"IPolicyManager","href":"Casbin.Policy.Types.IPolicyManager.htm"}
,{"title":"IPolicyManager.add(string)","href":"Casbin.Policy.Types.IPolicyManager.add.htm"}
,{"title":"IPolicyManager.clear","href":"Casbin.Policy.Types.IPolicyManager.clear.htm"}
,{"title":"IPolicyManager.load(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.load.htm"}
,{"title":"IPolicyManager.policies","href":"Casbin.Policy.Types.IPolicyManager.policies.htm"}
,{"title":"IPolicyManager.policy(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.policy.htm"}
,{"title":"IPolicyManager.policyExists(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.policyExists.htm"}
,{"title":"IPolicyManager.remove(string)","href":"Casbin.Policy.Types.IPolicyManager.remove(string).htm"}
,{"title":"IPolicyManager.remove(string,string)","href":"Casbin.Policy.Types.IPolicyManager.remove(string,string).htm"}
,{"title":"IPolicyManager.section(Boolean)","href":"Casbin.Policy.Types.IPolicyManager.section.htm"}
,{"title":"isNan(double)","href":"ParseClass.isNan.htm"}
,{"title":"ListChar","href":"ParseClass.ListChar.htm"}
,{"title":"matchersDefinition","href":"Casbin.Model.Sections.Default.matchersDefinition.htm"}
,{"title":"MaxArg","href":"ParseClass.MaxArg.htm"}
,{"title":"MaxCollectionSize","href":"OObjects.MaxCollectionSize.htm"}
,{"title":"mergeEffects(TEffectCondition,TEffectArray)","href":"Casbin.Effect.mergeEffects.htm"}
,{"title":"modelFileString","href":"Casbin.Core.Strings.modelFileString.htm"}
,{"title":"modelSections","href":"Casbin.Model.Sections.Types.modelSections.htm"}
,{"title":"Nan","href":"ParseClass.Nan.htm"}
,{"title":"OObjects","href":"OObjects.htm"}
,{"title":"OObjects.TNoOwnerCollection","href":"OObjects.TNoOwnerCollection.htm"}
,{"title":"OObjects.TOCollection","href":"OObjects.TOCollection.htm"}
,{"title":"OObjects.TSortedCollection","href":"OObjects.TSortedCollection.htm"}
,{"title":"OObjects.TStrCollection","href":"OObjects.TStrCollection.htm"}
,{"title":"ParseClass","href":"ParseClass.htm"}
,{"title":"ParseClass.EParserException","href":"ParseClass.EParserException.htm"}
,{"title":"ParseClass.PDouble","href":"ParseClass.PDouble.htm"}
,{"title":"ParseClass.PExpressionRec","href":"ParseClass.PExpressionRec.htm"}
,{"title":"ParseClass.PString","href":"ParseClass.PString.htm"}
,{"title":"ParseClass.TArgsArray","href":"ParseClass.TArgsArray.htm"}
,{"title":"ParseClass.TBooleanConstant","href":"ParseClass.TBooleanConstant.htm"}
,{"title":"ParseClass.TBooleanFunction","href":"ParseClass.TBooleanFunction.htm"}
,{"title":"ParseClass.TComma","href":"ParseClass.TComma.htm"}
,{"title":"ParseClass.TConstant","href":"ParseClass.TConstant.htm"}
,{"title":"ParseClass.TDoubleConstant","href":"ParseClass.TDoubleConstant.htm"}
,{"title":"ParseClass.TDoubleFunc","href":"ParseClass.TDoubleFunc.htm"}
,{"title":"ParseClass.TDoubleVariable","href":"ParseClass.TDoubleVariable.htm"}
,{"title":"ParseClass.TExprCollection","href":"ParseClass.TExprCollection.htm"}
,{"title":"ParseClass.TExpressionRec","href":"ParseClass.TExpressionRec.htm"}
,{"title":"ParseClass.TExpressList","href":"ParseClass.TExpressList.htm"}
,{"title":"ParseClass.TExprWord","href":"ParseClass.TExprWord.htm"}
,{"title":"ParseClass.TFunction","href":"ParseClass.TFunction.htm"}
,{"title":"ParseClass.TGeneratedVariable","href":"ParseClass.TGeneratedVariable.htm"}
,{"title":"ParseClass.TLeftBracket","href":"ParseClass.TLeftBracket.htm"}
,{"title":"ParseClass.TLogicalStringOper","href":"ParseClass.TLogicalStringOper.htm"}
,{"title":"ParseClass.TOper","href":"ParseClass.TOper.htm"}
,{"title":"ParseClass.TRightBracket","href":"ParseClass.TRightBracket.htm"}
,{"title":"ParseClass.TSimpleStringFunction","href":"ParseClass.TSimpleStringFunction.htm"}
,{"title":"ParseClass.TStringConstant","href":"ParseClass.TStringConstant.htm"}
,{"title":"ParseClass.TStringFunc","href":"ParseClass.TStringFunc.htm"}
,{"title":"ParseClass.TStringVariable","href":"ParseClass.TStringVariable.htm"}
,{"title":"ParseClass.TVarType","href":"ParseClass.TVarType.htm"}
,{"title":"ParseClass.TVaryingFunction","href":"ParseClass.TVaryingFunction.htm"}
,{"title":"ParseClass.TVaryingStringFunction","href":"ParseClass.TVaryingStringFunction.htm"}
,{"title":"ParseExpr","href":"ParseExpr.htm"}
,{"title":"ParseExpr.TCStyleParser","href":"ParseExpr.TCStyleParser.htm"}
,{"title":"ParseExpr.TCustomExpressionParser","href":"ParseExpr.TCustomExpressionParser.htm"}
,{"title":"ParseExpr.TExpressionParser","href":"ParseExpr.TExpressionParser.htm"}
,{"title":"PDouble","href":"ParseClass.PDouble.htm"}
,{"title":"PExpressionRec","href":"ParseClass.PExpressionRec.htm"}
,{"title":"policyDefinition","href":"Casbin.Model.Sections.Default.policyDefinition.htm"}
,{"title":"policyEffectDefinition","href":"Casbin.Model.Sections.Default.policyEffectDefinition.htm"}
,{"title":"policyFileString","href":"Casbin.Core.Strings.policyFileString.htm"}
,{"title":"policySections","href":"Casbin.Model.Sections.Types.policySections.htm"}
,{"title":"PString","href":"ParseClass.PString.htm"}
,{"title":"requestDefinition","href":"Casbin.Model.Sections.Default.requestDefinition.htm"}
,{"title":"roleDefinition","href":"Casbin.Model.Sections.Default.roleDefinition.htm"}
,{"title":"TArgsArray","href":"ParseClass.TArgsArray.htm"}
,{"title":"TArgsArray.Args","href":"ParseClass.TArgsArray.Args.htm"}
,{"title":"TArgsArray.ExprWord","href":"ParseClass.TArgsArray.ExprWord.htm"}
,{"title":"TArgsArray.Res","href":"ParseClass.TArgsArray.Res.htm"}
,{"title":"TAssertionNode","href":"Casbin.Parser.AST.Types.TAssertionNode.htm"}
,{"title":"TAssertionNode.toOutputString","href":"Casbin.Parser.AST.Types.TAssertionNode.toOutputString.htm"}
,{"title":"TBaseAdapter","href":"Casbin.Adapter.Base.TBaseAdapter.htm"}
,{"title":"TBaseAdapter.clear","href":"Casbin.Adapter.Base.TBaseAdapter.clear.htm"}
,{"title":"TBaseAdapter.Create","href":"Casbin.Adapter.Base.TBaseAdapter.Create.htm"}
,{"title":"TBaseAdapter.Destroy","href":"Casbin.Adapter.Base.TBaseAdapter.Destroy.htm"}
,{"title":"TBaseAdapter.fAssertions","href":"Casbin.Adapter.Base.TBaseAdapter.fAssertions.htm"}
,{"title":"TBaseAdapter.fFilter","href":"Casbin.Adapter.Base.TBaseAdapter.fFilter.htm"}
,{"title":"TBaseAdapter.fFiltered","href":"Casbin.Adapter.Base.TBaseAdapter.fFiltered.htm"}
,{"title":"TBaseAdapter.fLogger","href":"Casbin.Adapter.Base.TBaseAdapter.fLogger.htm"}
,{"title":"TBaseAdapter.getAssertions","href":"Casbin.Adapter.Base.TBaseAdapter.getAssertions.htm"}
,{"title":"TBaseAdapter.getFilter","href":"Casbin.Adapter.Base.TBaseAdapter.getFilter.htm"}
,{"title":"TBaseAdapter.getFiltered","href":"Casbin.Adapter.Base.TBaseAdapter.getFiltered.htm"}
,{"title":"TBaseAdapter.getLogger","href":"Casbin.Adapter.Base.TBaseAdapter.getLogger.htm"}
,{"title":"TBaseAdapter.load(TFilterArray)","href":"Casbin.Adapter.Base.TBaseAdapter.load.htm"}
,{"title":"TBaseAdapter.save","href":"Casbin.Adapter.Base.TBaseAdapter.save.htm"}
,{"title":"TBaseAdapter.setAssertions(TList)","href":"Casbin.Adapter.Base.TBaseAdapter.setAssertions.htm"}
,{"title":"TBaseAdapter.setLogger(ILogger)","href":"Casbin.Adapter.Base.TBaseAdapter.setLogger.htm"}
,{"title":"TBaseAdapter.toOutputString","href":"Casbin.Adapter.Base.TBaseAdapter.toOutputString.htm"}
,{"title":"TBaseInterfacedObject","href":"Casbin.Core.Base.Types.TBaseInterfacedObject.htm"}
,{"title":"TBaseLogger","href":"Casbin.Core.Logger.Base.TBaseLogger.htm"}
,{"title":"TBaseLogger.Create","href":"Casbin.Core.Logger.Base.TBaseLogger.Create.htm"}
,{"title":"TBaseLogger.fEnabled","href":"Casbin.Core.Logger.Base.TBaseLogger.fEnabled.htm"}
,{"title":"TBaseLogger.fLastLoggedMessage","href":"Casbin.Core.Logger.Base.TBaseLogger.fLastLoggedMessage.htm"}
,{"title":"TBaseLogger.getEnabled","href":"Casbin.Core.Logger.Base.TBaseLogger.getEnabled.htm"}
,{"title":"TBaseLogger.getLastLoggedMessage","href":"Casbin.Core.Logger.Base.TBaseLogger.getLastLoggedMessage.htm"}
,{"title":"TBaseLogger.log(string)","href":"Casbin.Core.Logger.Base.TBaseLogger.log.htm"}
,{"title":"TBaseLogger.setEnabled(Boolean)","href":"Casbin.Core.Logger.Base.TBaseLogger.setEnabled.htm"}
,{"title":"TBaseNode","href":"Casbin.Parser.AST.Types.TBaseNode.htm"}
,{"title":"TBaseNode.fKey","href":"Casbin.Parser.AST.Types.TBaseNode.fKey.htm"}
,{"title":"TBaseNode.fValue","href":"Casbin.Parser.AST.Types.TBaseNode.fValue.htm"}
,{"title":"TBaseNode.Key","href":"Casbin.Parser.AST.Types.TBaseNode.Key.htm"}
,{"title":"TBaseNode.toOutputString","href":"Casbin.Parser.AST.Types.TBaseNode.toOutputString.htm"}
,{"title":"TBaseNode.Value","href":"Casbin.Parser.AST.Types.TBaseNode.Value.htm"}
,{"title":"TBaseObject","href":"Casbin.Core.Base.Types.TBaseObject.htm"}
,{"title":"TBooleanConstant","href":"ParseClass.TBooleanConstant.htm"}
,{"title":"TBooleanConstant.GetVarType","href":"ParseClass.TBooleanConstant.GetVarType.htm"}
,{"title":"TBooleanFunction","href":"ParseClass.TBooleanFunction.htm"}
,{"title":"TBooleanFunction.GetVarType","href":"ParseClass.TBooleanFunction.GetVarType.htm"}
,{"title":"TCasbinFunc","href":"Casbin.Functions.Types.TCasbinFunc.htm"}
,{"title":"TChildNode","href":"Casbin.Parser.AST.Types.TChildNode.htm"}
,{"title":"TChildNode.AssertionList","href":"Casbin.Parser.AST.Types.TChildNode.AssertionList.htm"}
,{"title":"TChildNode.Create","href":"Casbin.Parser.AST.Types.TChildNode.Create.htm"}
,{"title":"TChildNode.Destroy","href":"Casbin.Parser.AST.Types.TChildNode.Destroy.htm"}
,{"title":"TChildNode.fAssertionList","href":"Casbin.Parser.AST.Types.TChildNode.fAssertionList.htm"}
,{"title":"TChildNode.toOutputString","href":"Casbin.Parser.AST.Types.TChildNode.toOutputString.htm"}
,{"title":"TComma","href":"ParseClass.TComma.htm"}
,{"title":"TComma.GetVarType","href":"ParseClass.TComma.GetVarType.htm"}
,{"title":"TConstant","href":"ParseClass.TConstant.htm"}
,{"title":"TConstant.CreateAsDouble(string,string,Double)","href":"ParseClass.TConstant.CreateAsDouble.htm"}
,{"title":"TConstant.FDescription","href":"ParseClass.TConstant.FDescription.htm"}
,{"title":"TConstant.GetDescription","href":"ParseClass.TConstant.GetDescription.htm"}
,{"title":"TCStyleParser","href":"ParseExpr.TCStyleParser.htm"}
,{"title":"TCStyleParser.CStyle","href":"ParseExpr.TCStyleParser.CStyle.htm"}
,{"title":"TCStyleParser.FCStyle","href":"ParseExpr.TCStyleParser.FCStyle.htm"}
,{"title":"TCStyleParser.FillExpressList","href":"ParseExpr.TCStyleParser.FillExpressList.htm"}
,{"title":"TCStyleParser.SetCStyle(Boolean)","href":"ParseExpr.TCStyleParser.SetCStyle.htm"}
,{"title":"TCustomExpressionParser","href":"ParseExpr.TCustomExpressionParser.htm"}
,{"title":"TCustomExpressionParser.AddExpression(string)","href":"ParseExpr.TCustomExpressionParser.AddExpression.htm"}
,{"title":"TCustomExpressionParser.AddReplaceExprWord(TExprWord)","href":"ParseExpr.TCustomExpressionParser.AddReplaceExprWord.htm"}
,{"title":"TCustomExpressionParser.ArgSeparator","href":"ParseExpr.TCustomExpressionParser.ArgSeparator.htm"}
,{"title":"TCustomExpressionParser.Check(TExprCollection)","href":"ParseExpr.TCustomExpressionParser.Check.htm"}
,{"title":"TCustomExpressionParser.CheckArguments(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.CheckArguments.htm"}
,{"title":"TCustomExpressionParser.ClearExpressions","href":"ParseExpr.TCustomExpressionParser.ClearExpressions.htm"}
,{"title":"TCustomExpressionParser.CompileExpression(string)","href":"ParseExpr.TCustomExpressionParser.CompileExpression.htm"}
,{"title":"TCustomExpressionParser.ConstantsList","href":"ParseExpr.TCustomExpressionParser.ConstantsList.htm"}
,{"title":"TCustomExpressionParser.Create","href":"ParseExpr.TCustomExpressionParser.Create.htm"}
,{"title":"TCustomExpressionParser.CurrentExpression","href":"ParseExpr.TCustomExpressionParser.CurrentExpression.htm"}
,{"title":"TCustomExpressionParser.CurrentRec","href":"ParseExpr.TCustomExpressionParser.CurrentRec.htm"}
,{"title":"TCustomExpressionParser.DecimSeparator","href":"ParseExpr.TCustomExpressionParser.DecimSeparator.htm"}
,{"title":"TCustomExpressionParser.DefineFunction(string,string,TDoubleFunc,Integer)","href":"ParseExpr.TCustomExpressionParser.DefineFunction.htm"}
,{"title":"TCustomExpressionParser.DefineStringFunction(string,string,TStringFunc)","href":"ParseExpr.TCustomExpressionParser.DefineStringFunction.htm"}
,{"title":"TCustomExpressionParser.DefineStringVariable(string,PString)","href":"ParseExpr.TCustomExpressionParser.DefineStringVariable.htm"}
,{"title":"TCustomExpressionParser.DefineVariable(string,PDouble)","href":"ParseExpr.TCustomExpressionParser.DefineVariable.htm"}
,{"title":"TCustomExpressionParser.Destroy","href":"ParseExpr.TCustomExpressionParser.Destroy.htm"}
,{"title":"TCustomExpressionParser.DisposeList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.DisposeList.htm"}
,{"title":"TCustomExpressionParser.DisposeTree(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.DisposeTree.htm"}
,{"title":"TCustomExpressionParser.Evaluate(string)","href":"ParseExpr.TCustomExpressionParser.Evaluate.htm"}
,{"title":"TCustomExpressionParser.EvaluateCurrent","href":"ParseExpr.TCustomExpressionParser.EvaluateCurrent.htm"}
,{"title":"TCustomExpressionParser.EvaluateDisposeTree(PExpressionRec,Boolean)","href":"ParseExpr.TCustomExpressionParser.EvaluateDisposeTree.htm"}
,{"title":"TCustomExpressionParser.EvaluateList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.EvaluateList.htm"}
,{"title":"TCustomExpressionParser.FArgSeparator","href":"ParseExpr.TCustomExpressionParser.FArgSeparator.htm"}
,{"title":"TCustomExpressionParser.FDecimSeparator","href":"ParseExpr.TCustomExpressionParser.FDecimSeparator.htm"}
,{"title":"TCustomExpressionParser.FHexChar","href":"ParseExpr.TCustomExpressionParser.FHexChar.htm"}
,{"title":"TCustomExpressionParser.FillExpressList","href":"ParseExpr.TCustomExpressionParser.FillExpressList.htm"}
,{"title":"TCustomExpressionParser.FOptimize","href":"ParseExpr.TCustomExpressionParser.FOptimize.htm"}
,{"title":"TCustomExpressionParser.GetFunctionDescription(string)","href":"ParseExpr.TCustomExpressionParser.GetFunctionDescription.htm"}
,{"title":"TCustomExpressionParser.GetFunctionNames(TStrings)","href":"ParseExpr.TCustomExpressionParser.GetFunctionNames.htm"}
,{"title":"TCustomExpressionParser.GetGeneratedVars(TList)","href":"ParseExpr.TCustomExpressionParser.GetGeneratedVars.htm"}
,{"title":"TCustomExpressionParser.HexChar","href":"ParseExpr.TCustomExpressionParser.HexChar.htm"}
,{"title":"TCustomExpressionParser.isBoolean","href":"ParseExpr.TCustomExpressionParser.isBoolean.htm"}
,{"title":"TCustomExpressionParser.LastRec","href":"ParseExpr.TCustomExpressionParser.LastRec.htm"}
,{"title":"TCustomExpressionParser.MakeLinkedList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.MakeLinkedList.htm"}
,{"title":"TCustomExpressionParser.MakeRec","href":"ParseExpr.TCustomExpressionParser.MakeRec.htm"}
,{"title":"TCustomExpressionParser.MakeTree(TExprCollection)","href":"ParseExpr.TCustomExpressionParser.MakeTree.htm"}
,{"title":"TCustomExpressionParser.Optimize","href":"ParseExpr.TCustomExpressionParser.Optimize.htm"}
,{"title":"TCustomExpressionParser.ParseString(string)","href":"ParseExpr.TCustomExpressionParser.ParseString.htm"}
,{"title":"TCustomExpressionParser.RemoveConstants(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.RemoveConstants.htm"}
,{"title":"TCustomExpressionParser.ReplaceExprWord(TExprWord,TExprWord)","href":"ParseExpr.TCustomExpressionParser.ReplaceExprWord.htm"}
,{"title":"TCustomExpressionParser.ReplaceFunction(string,TObject)","href":"ParseExpr.TCustomExpressionParser.ReplaceFunction.htm"}
,{"title":"TCustomExpressionParser.ResultCanVary(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.ResultCanVary.htm"}
,{"title":"TCustomExpressionParser.SetArgSeparator(Char)","href":"ParseExpr.TCustomExpressionParser.SetArgSeparator.htm"}
,{"title":"TCustomExpressionParser.SetDecimSeparator(Char)","href":"ParseExpr.TCustomExpressionParser.SetDecimSeparator.htm"}
,{"title":"TCustomExpressionParser.WordsList","href":"ParseExpr.TCustomExpressionParser.WordsList.htm"}
,{"title":"TDefaultLogger","href":"Casbin.Core.Logger.Default.TDefaultLogger.htm"}
,{"title":"TDefaultLogger.log(string)","href":"Casbin.Core.Logger.Default.TDefaultLogger.log.htm"}
,{"title":"TDoubleConstant","href":"ParseClass.TDoubleConstant.htm"}
,{"title":"TDoubleConstant.AsPointer","href":"ParseClass.TDoubleConstant.AsPointer.htm"}
,{"title":"TDoubleConstant.Create(string,string)","href":"ParseClass.TDoubleConstant.Create.htm"}
,{"title":"TDoubleConstant.CreateAsDouble(string,Double)","href":"ParseClass.TDoubleConstant.CreateAsDouble.htm"}
,{"title":"TDoubleConstant.FValue","href":"ParseClass.TDoubleConstant.FValue.htm"}
,{"title":"TDoubleConstant.Value","href":"ParseClass.TDoubleConstant.Value.htm"}
,{"title":"TDoubleFunc","href":"ParseClass.TDoubleFunc.htm"}
,{"title":"TDoubleVariable","href":"ParseClass.TDoubleVariable.htm"}
,{"title":"TDoubleVariable.AsPointer","href":"ParseClass.TDoubleVariable.AsPointer.htm"}
,{"title":"TDoubleVariable.Create(string,PDouble)","href":"ParseClass.TDoubleVariable.Create.htm"}
,{"title":"TDoubleVariable.FValue","href":"ParseClass.TDoubleVariable.FValue.htm"}
,{"title":"TDoubleVariable.GetCanVary","href":"ParseClass.TDoubleVariable.GetCanVary.htm"}
,{"title":"TEffectArray","href":"Casbin.Effect.Types.TEffectArray.htm"}
,{"title":"TEffectCondition","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectCondition.ecNotSomeDeny","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectCondition.ecPriorityORDeny","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectCondition.ecSomeAllow","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectCondition.ecSomeAllowANDNotDeny","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectCondition.ecUnknown","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectNode","href":"Casbin.Parser.AST.Types.TEffectNode.htm"}
,{"title":"TEffectNode.EffectCondition","href":"Casbin.Parser.AST.Types.TEffectNode.EffectCondition.htm"}
,{"title":"TEffectNode.fEffectCondition","href":"Casbin.Parser.AST.Types.TEffectNode.fEffectCondition.htm"}
,{"title":"TEffectResult","href":"Casbin.Effect.Types.TEffectResult.htm"}
,{"title":"TEffectResult.erAllow","href":"Casbin.Effect.Types.TEffectResult.htm"}
,{"title":"TEffectResult.erDeny","href":"Casbin.Effect.Types.TEffectResult.htm"}
,{"title":"TEffectResult.erIndeterminate","href":"Casbin.Effect.Types.TEffectResult.htm"}
,{"title":"TExprCollection","href":"ParseClass.TExprCollection.htm"}
,{"title":"TExprCollection.Check","href":"ParseClass.TExprCollection.Check.htm"}
,{"title":"TExprCollection.EraseExtraBrackets","href":"ParseClass.TExprCollection.EraseExtraBrackets.htm"}
,{"title":"TExprCollection.NextOper(Integer)","href":"ParseClass.TExprCollection.NextOper.htm"}
,{"title":"TExpressionParser","href":"ParseExpr.TExpressionParser.htm"}
,{"title":"TExpressionParser.AddExpression(string)","href":"ParseExpr.TExpressionParser.AddExpression.htm"}
,{"title":"TExpressionParser.AsBoolean[Integer]","href":"ParseExpr.TExpressionParser.AsBoolean[Integer].htm"}
,{"title":"TExpressionParser.AsFloat[Integer]","href":"ParseExpr.TExpressionParser.AsFloat[Integer].htm"}
,{"title":"TExpressionParser.AsHexadecimal[Integer]","href":"ParseExpr.TExpressionParser.AsHexadecimal[Integer].htm"}
,{"title":"TExpressionParser.AsString[Integer]","href":"ParseExpr.TExpressionParser.AsString[Integer].htm"}
,{"title":"TExpressionParser.ClearExpressions","href":"ParseExpr.TExpressionParser.ClearExpressions.htm"}
,{"title":"TExpressionParser.Create","href":"ParseExpr.TExpressionParser.Create.htm"}
,{"title":"TExpressionParser.CurrentExpression","href":"ParseExpr.TExpressionParser.CurrentExpression.htm"}
,{"title":"TExpressionParser.CurrentIndex","href":"ParseExpr.TExpressionParser.CurrentIndex.htm"}
,{"title":"TExpressionParser.Destroy","href":"ParseExpr.TExpressionParser.Destroy.htm"}
,{"title":"TExpressionParser.Expression[Integer]","href":"ParseExpr.TExpressionParser.Expression[Integer].htm"}
,{"title":"TExpressionParser.Expressions","href":"ParseExpr.TExpressionParser.Expressions.htm"}
,{"title":"TExpressionParser.ExpressionSize[Integer]","href":"ParseExpr.TExpressionParser.ExpressionSize[Integer].htm"}
,{"title":"TExpressionParser.FCurrentIndex","href":"ParseExpr.TExpressionParser.FCurrentIndex.htm"}
,{"title":"TExpressionParser.FillExpressList","href":"ParseExpr.TExpressionParser.FillExpressList.htm"}
,{"title":"TExpressionParser.GetAsBoolean(Integer)","href":"ParseExpr.TExpressionParser.GetAsBoolean.htm"}
,{"title":"TExpressionParser.GetAsHexadecimal(Integer)","href":"ParseExpr.TExpressionParser.GetAsHexadecimal.htm"}
,{"title":"TExpressionParser.GetAsString(Integer)","href":"ParseExpr.TExpressionParser.GetAsString.htm"}
,{"title":"TExpressionParser.GetExpression(Integer)","href":"ParseExpr.TExpressionParser.GetExpression.htm"}
,{"title":"TExpressionParser.GetExprSize(Integer)","href":"ParseExpr.TExpressionParser.GetExprSize.htm"}
,{"title":"TExpressionParser.GetResults(Integer)","href":"ParseExpr.TExpressionParser.GetResults.htm"}
,{"title":"TExpressionParser.ReplaceExprWord(TExprWord,TExprWord)","href":"ParseExpr.TExpressionParser.ReplaceExprWord.htm"}
,{"title":"TExpressionRec","href":"ParseClass.TExpressionRec.htm"}
,{"title":"TExpressionRec.ArgList","href":"ParseClass.TExpressionRec.ArgList.htm"}
,{"title":"TExpressionRec.Args","href":"ParseClass.TExpressionRec.Args.htm"}
,{"title":"TExpressionRec.ExprWord","href":"ParseClass.TExpressionRec.ExprWord.htm"}
,{"title":"TExpressionRec.Next","href":"ParseClass.TExpressionRec.Next.htm"}
,{"title":"TExpressionRec.Oper","href":"ParseClass.TExpressionRec.Oper.htm"}
,{"title":"TExpressionRec.Res","href":"ParseClass.TExpressionRec.Res.htm"}
,{"title":"TExpressList","href":"ParseClass.TExpressList.htm"}
,{"title":"TExpressList.Compare(Pointer,Pointer)","href":"ParseClass.TExpressList.Compare.htm"}
,{"title":"TExpressList.KeyOf(Pointer)","href":"ParseClass.TExpressList.KeyOf.htm"}
,{"title":"TExprWord","href":"ParseClass.TExprWord.htm"}
,{"title":"TExprWord.AsPointer","href":"ParseClass.TExprWord.AsPointer.htm"}
,{"title":"TExprWord.AsString","href":"ParseClass.TExprWord.AsString.htm"}
,{"title":"TExprWord.CanVary","href":"ParseClass.TExprWord.CanVary.htm"}
,{"title":"TExprWord.Create(string,TDoubleFunc)","href":"ParseClass.TExprWord.Create.htm"}
,{"title":"TExprWord.Description","href":"ParseClass.TExprWord.Description.htm"}
,{"title":"TExprWord.DoubleFunc","href":"ParseClass.TExprWord.DoubleFunc.htm"}
,{"title":"TExprWord.FDoubleFunc","href":"ParseClass.TExprWord.FDoubleFunc.htm"}
,{"title":"TExprWord.FName","href":"ParseClass.TExprWord.FName.htm"}
,{"title":"TExprWord.GetAsString","href":"ParseClass.TExprWord.GetAsString.htm"}
,{"title":"TExprWord.GetCanVary","href":"ParseClass.TExprWord.GetCanVary.htm"}
,{"title":"TExprWord.GetDescription","href":"ParseClass.TExprWord.GetDescription.htm"}
,{"title":"TExprWord.GetIsOper","href":"ParseClass.TExprWord.GetIsOper.htm"}
,{"title":"TExprWord.GetIsVariable","href":"ParseClass.TExprWord.GetIsVariable.htm"}
,{"title":"TExprWord.GetNFunctionArg","href":"ParseClass.TExprWord.GetNFunctionArg.htm"}
,{"title":"TExprWord.GetVarType","href":"ParseClass.TExprWord.GetVarType.htm"}
,{"title":"TExprWord.IsOper","href":"ParseClass.TExprWord.IsOper.htm"}
,{"title":"TExprWord.isVariable","href":"ParseClass.TExprWord.isVariable.htm"}
,{"title":"TExprWord.Name","href":"ParseClass.TExprWord.Name.htm"}
,{"title":"TExprWord.NFunctionArg","href":"ParseClass.TExprWord.NFunctionArg.htm"}
,{"title":"TExprWord.VarType","href":"ParseClass.TExprWord.VarType.htm"}
,{"title":"TFileAdapter","href":"Casbin.Adapter.Filesystem.TFileAdapter.htm"}
,{"title":"TFileAdapter.Create(string)","href":"Casbin.Adapter.Filesystem.TFileAdapter.Create.htm"}
,{"title":"TFileAdapter.fFilename","href":"Casbin.Adapter.Filesystem.TFileAdapter.fFilename.htm"}
,{"title":"TFileAdapter.load(TFilterArray)","href":"Casbin.Adapter.Filesystem.TFileAdapter.load.htm"}
,{"title":"TFileAdapter.save","href":"Casbin.Adapter.Filesystem.TFileAdapter.save.htm"}
,{"title":"TFilterArray","href":"Casbin.Core.Base.Types.TFilterArray.htm"}
,{"title":"TFunction","href":"ParseClass.TFunction.htm"}
,{"title":"TFunction.Create(string,string,TDoubleFunc,Integer)","href":"ParseClass.TFunction.Create.htm"}
,{"title":"TFunction.CreateOper(string,TDoubleFunc,Integer,Boolean,Integer)","href":"ParseClass.TFunction.CreateOper.htm"}
,{"title":"TFunction.FDescription","href":"ParseClass.TFunction.FDescription.htm"}
,{"title":"TFunction.FIsOper","href":"ParseClass.TFunction.FIsOper.htm"}
,{"title":"TFunction.FNFunctionArg","href":"ParseClass.TFunction.FNFunctionArg.htm"}
,{"title":"TFunction.FOperPrec","href":"ParseClass.TFunction.FOperPrec.htm"}
,{"title":"TFunction.GetDescription","href":"ParseClass.TFunction.GetDescription.htm"}
,{"title":"TFunction.GetIsOper","href":"ParseClass.TFunction.GetIsOper.htm"}
,{"title":"TFunction.GetNFunctionArg","href":"ParseClass.TFunction.GetNFunctionArg.htm"}
,{"title":"TFunction.OperPrec","href":"ParseClass.TFunction.OperPrec.htm"}
,{"title":"TFunctions","href":"Casbin.Functions.TFunctions.htm"}
,{"title":"TFunctions.Create","href":"Casbin.Functions.TFunctions.Create.htm"}
,{"title":"TFunctions.Destroy","href":"Casbin.Functions.TFunctions.Destroy.htm"}
,{"title":"TFunctions.fDictionary","href":"Casbin.Functions.TFunctions.fDictionary.htm"}
,{"title":"TFunctions.list","href":"Casbin.Functions.TFunctions.list.htm"}
,{"title":"TFunctions.loadBuiltInFunctions","href":"Casbin.Functions.TFunctions.loadBuiltInFunctions.htm"}
,{"title":"TFunctions.loadCustomFunctions","href":"Casbin.Functions.TFunctions.loadCustomFunctions.htm"}
,{"title":"TFunctions.refreshFunctions","href":"Casbin.Functions.TFunctions.refreshFunctions.htm"}
,{"title":"TFunctions.registerFunction(string,TCasbinFunc)","href":"Casbin.Functions.TFunctions.registerFunction.htm"}
,{"title":"TFunctions.retrieveFunction(string)","href":"Casbin.Functions.TFunctions.retrieveFunction.htm"}
,{"title":"TGeneratedVariable","href":"ParseClass.TGeneratedVariable.htm"}
,{"title":"TGeneratedVariable.AsString","href":"ParseClass.TGeneratedVariable.AsString.htm"}
,{"title":"TGeneratedVariable.Create(string)","href":"ParseClass.TGeneratedVariable.Create.htm"}
,{"title":"TGeneratedVariable.FAsString","href":"ParseClass.TGeneratedVariable.FAsString.htm"}
,{"title":"TGeneratedVariable.FVarType","href":"ParseClass.TGeneratedVariable.FVarType.htm"}
,{"title":"TGeneratedVariable.GetAsString","href":"ParseClass.TGeneratedVariable.GetAsString.htm"}
,{"title":"TGeneratedVariable.GetCanVary","href":"ParseClass.TGeneratedVariable.GetCanVary.htm"}
,{"title":"TGeneratedVariable.GetVarType","href":"ParseClass.TGeneratedVariable.GetVarType.htm"}
,{"title":"TGeneratedVariable.VarType","href":"ParseClass.TGeneratedVariable.VarType.htm"}
,{"title":"THeaderNode","href":"Casbin.Parser.AST.Types.THeaderNode.htm"}
,{"title":"THeaderNode.ChildNodes","href":"Casbin.Parser.AST.Types.THeaderNode.ChildNodes.htm"}
,{"title":"THeaderNode.Create","href":"Casbin.Parser.AST.Types.THeaderNode.Create.htm"}
,{"title":"THeaderNode.Destroy","href":"Casbin.Parser.AST.Types.THeaderNode.Destroy.htm"}
,{"title":"THeaderNode.fSectionType","href":"Casbin.Parser.AST.Types.THeaderNode.fSectionType.htm"}
,{"title":"THeaderNode.fStatementNode","href":"Casbin.Parser.AST.Types.THeaderNode.fStatementNode.htm"}
,{"title":"THeaderNode.SectionType","href":"Casbin.Parser.AST.Types.THeaderNode.SectionType.htm"}
,{"title":"THeaderNode.toOutputString","href":"Casbin.Parser.AST.Types.THeaderNode.toOutputString.htm"}
,{"title":"TLeftBracket","href":"ParseClass.TLeftBracket.htm"}
,{"title":"TLeftBracket.GetVarType","href":"ParseClass.TLeftBracket.GetVarType.htm"}
,{"title":"TLogicalStringOper","href":"ParseClass.TLogicalStringOper.htm"}
,{"title":"TLogicalStringOper.Create(string,TExprWord,TExprWord)","href":"ParseClass.TLogicalStringOper.Create.htm"}
,{"title":"TLogicalStringOper.GetVarType","href":"ParseClass.TLogicalStringOper.GetVarType.htm"}
,{"title":"TMatcher","href":"Casbin.Matcher.TMatcher.htm"}
,{"title":"TMatcher.cleanMatcher","href":"Casbin.Matcher.TMatcher.cleanMatcher.htm"}
,{"title":"TMatcher.Create","href":"Casbin.Matcher.TMatcher.Create.htm"}
,{"title":"TMatcher.Destroy","href":"Casbin.Matcher.TMatcher.Destroy.htm"}
,{"title":"TMatcher.evaluateMatcher(string)","href":"Casbin.Matcher.TMatcher.evaluateMatcher.htm"}
,{"title":"TMatcher.fMatcherString","href":"Casbin.Matcher.TMatcher.fMatcherString.htm"}
,{"title":"TMatcher.fMathsParser","href":"Casbin.Matcher.TMatcher.fMathsParser.htm"}
,{"title":"TModel","href":"Casbin.Model.TModel.htm"}
,{"title":"TModel.assertions(TSectionType)","href":"Casbin.Model.TModel.assertions.htm"}
,{"title":"TModel.checkSection(TSectionType)","href":"Casbin.Model.TModel.checkSection.htm"}
,{"title":"TModel.Create(IAdapter)","href":"Casbin.Model.TModel.Create(IAdapter).htm"}
,{"title":"TModel.Create(string)","href":"Casbin.Model.TModel.Create(string).htm"}
,{"title":"TModel.fAdapter","href":"Casbin.Model.TModel.fAdapter.htm"}
,{"title":"TModel.fNodes","href":"Casbin.Model.TModel.fNodes.htm"}
,{"title":"TModel.fParser","href":"Casbin.Model.TModel.fParser.htm"}
,{"title":"TModel.section(TSectionType,Boolean)","href":"Casbin.Model.TModel.section.htm"}
,{"title":"TNodeCollection","href":"Casbin.Parser.AST.Types.TNodeCollection.htm"}
,{"title":"TNodeCollection.Create","href":"Casbin.Parser.AST.Types.TNodeCollection.Create.htm"}
,{"title":"TNodeCollection.Destroy","href":"Casbin.Parser.AST.Types.TNodeCollection.Destroy.htm"}
,{"title":"TNodeCollection.fHeaders","href":"Casbin.Parser.AST.Types.TNodeCollection.fHeaders.htm"}
,{"title":"TNodeCollection.Headers","href":"Casbin.Parser.AST.Types.TNodeCollection.Headers.htm"}
,{"title":"TNodeCollection.toOutputString","href":"Casbin.Parser.AST.Types.TNodeCollection.toOutputString.htm"}
,{"title":"TNoOwnerCollection","href":"OObjects.TNoOwnerCollection.htm"}
,{"title":"TNoOwnerCollection.FreeItem(Pointer)","href":"OObjects.TNoOwnerCollection.FreeItem.htm"}
,{"title":"TOCollection","href":"OObjects.TOCollection.htm"}
,{"title":"TOCollection.AtFree(Integer)","href":"OObjects.TOCollection.AtFree.htm"}
,{"title":"TOCollection.Create(Integer)","href":"OObjects.TOCollection.Create.htm"}
,{"title":"TOCollection.Destroy","href":"OObjects.TOCollection.Destroy.htm"}
,{"title":"TOCollection.DoFree(Pointer)","href":"OObjects.TOCollection.DoFree.htm"}
,{"title":"TOCollection.FreeAll","href":"OObjects.TOCollection.FreeAll.htm"}
,{"title":"TOCollection.FreeItem(Pointer)","href":"OObjects.TOCollection.FreeItem.htm"}
,{"title":"TOper","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_eq","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_ge","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_gt","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_in","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_le","href":"ParseClass.TOper.htm"}
,{"title":"TOper.op_lt","href":"ParseClass.TOper.htm"}
,{"title":"TParser","href":"Casbin.Parser.TParser.htm"}
,{"title":"TParser.checkHeaders","href":"Casbin.Parser.TParser.checkHeaders.htm"}
,{"title":"TParser.checkSyntaxErrors","href":"Casbin.Parser.TParser.checkSyntaxErrors.htm"}
,{"title":"TParser.cleanWhiteSpace","href":"Casbin.Parser.TParser.cleanWhiteSpace.htm"}
,{"title":"TParser.Create(string,TParseType)","href":"Casbin.Parser.TParser.Create.htm"}
,{"title":"TParser.Destroy","href":"Casbin.Parser.TParser.Destroy.htm"}
,{"title":"TParser.fErrorMessage","href":"Casbin.Parser.TParser.fErrorMessage.htm"}
,{"title":"TParser.fLogger","href":"Casbin.Parser.TParser.fLogger.htm"}
,{"title":"TParser.fNodes","href":"Casbin.Parser.TParser.fNodes.htm"}
,{"title":"TParser.fParseString","href":"Casbin.Parser.TParser.fParseString.htm"}
,{"title":"TParser.fParseType","href":"Casbin.Parser.TParser.fParseType.htm"}
,{"title":"TParser.fStatus","href":"Casbin.Parser.TParser.fStatus.htm"}
,{"title":"TParser.getErrorMessage","href":"Casbin.Parser.TParser.getErrorMessage.htm"}
,{"title":"TParser.getLogger","href":"Casbin.Parser.TParser.getLogger.htm"}
,{"title":"TParser.getNodes","href":"Casbin.Parser.TParser.getNodes.htm"}
,{"title":"TParser.getParseType","href":"Casbin.Parser.TParser.getParseType.htm"}
,{"title":"TParser.getStatus","href":"Casbin.Parser.TParser.getStatus.htm"}
,{"title":"TParser.parse","href":"Casbin.Parser.TParser.parse.htm"}
,{"title":"TParser.parseContent","href":"Casbin.Parser.TParser.parseContent.htm"}
,{"title":"TParser.setLogger(ILogger)","href":"Casbin.Parser.TParser.setLogger.htm"}
,{"title":"TParserStatus","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"TParserStatus.psError","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"TParserStatus.psIdle","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"TParserStatus.psRunning","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"TParseType","href":"Casbin.Parser.Types.TParseType.htm"}
,{"title":"TParseType.ptConfig","href":"Casbin.Parser.Types.TParseType.htm"}
,{"title":"TParseType.ptModel","href":"Casbin.Parser.Types.TParseType.htm"}
,{"title":"TParseType.ptPolicy","href":"Casbin.Parser.Types.TParseType.htm"}
,{"title":"TPolicyFileAdapter","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.htm"}
,{"title":"TPolicyFileAdapter.add(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.add.htm"}
,{"title":"TPolicyFileAdapter.Create(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.Create.htm"}
,{"title":"TPolicyFileAdapter.fAutosave","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fAutosave.htm"}
,{"title":"TPolicyFileAdapter.fCached","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCached.htm"}
,{"title":"TPolicyFileAdapter.fCacheSize","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCacheSize.htm"}
,{"title":"TPolicyFileAdapter.getAutoSave","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getAutoSave.htm"}
,{"title":"TPolicyFileAdapter.getCached","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCached.htm"}
,{"title":"TPolicyFileAdapter.getCacheSize","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCacheSize.htm"}
,{"title":"TPolicyFileAdapter.load(TFilterArray)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.load.htm"}
,{"title":"TPolicyFileAdapter.remove(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string).htm"}
,{"title":"TPolicyFileAdapter.remove(string,string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string,string).htm"}
,{"title":"TPolicyFileAdapter.save","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.save.htm"}
,{"title":"TPolicyFileAdapter.setAutoSave(Boolean)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setAutoSave.htm"}
,{"title":"TPolicyFileAdapter.setCached(Boolean)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCached.htm"}
,{"title":"TPolicyFileAdapter.setCacheSize(Integer)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCacheSize.htm"}
,{"title":"TPolicyManager","href":"Casbin.Policy.TPolicyManager.htm"}
,{"title":"TPolicyManager.add(string)","href":"Casbin.Policy.TPolicyManager.add.htm"}
,{"title":"TPolicyManager.clear","href":"Casbin.Policy.TPolicyManager.clear.htm"}
,{"title":"TPolicyManager.Create(IPolicyAdapter)","href":"Casbin.Policy.TPolicyManager.Create(IPolicyAdapter).htm"}
,{"title":"TPolicyManager.Create(string)","href":"Casbin.Policy.TPolicyManager.Create(string).htm"}
,{"title":"TPolicyManager.fAdapter","href":"Casbin.Policy.TPolicyManager.fAdapter.htm"}
,{"title":"TPolicyManager.fNodes","href":"Casbin.Policy.TPolicyManager.fNodes.htm"}
,{"title":"TPolicyManager.fParser","href":"Casbin.Policy.TPolicyManager.fParser.htm"}
,{"title":"TPolicyManager.load(TFilterArray)","href":"Casbin.Policy.TPolicyManager.load.htm"}
,{"title":"TPolicyManager.loadPolicies","href":"Casbin.Policy.TPolicyManager.loadPolicies.htm"}
,{"title":"TPolicyManager.policies","href":"Casbin.Policy.TPolicyManager.policies.htm"}
,{"title":"TPolicyManager.policy(TFilterArray)","href":"Casbin.Policy.TPolicyManager.policy.htm"}
,{"title":"TPolicyManager.policyExists(TFilterArray)","href":"Casbin.Policy.TPolicyManager.policyExists.htm"}
,{"title":"TPolicyManager.remove(string)","href":"Casbin.Policy.TPolicyManager.remove(string).htm"}
,{"title":"TPolicyManager.remove(string,string)","href":"Casbin.Policy.TPolicyManager.remove(string,string).htm"}
,{"title":"TPolicyManager.section(Boolean)","href":"Casbin.Policy.TPolicyManager.section.htm"}
,{"title":"TRightBracket","href":"ParseClass.TRightBracket.htm"}
,{"title":"TRightBracket.GetVarType","href":"ParseClass.TRightBracket.GetVarType.htm"}
,{"title":"TSection","href":"Casbin.Model.Sections.Types.TSection.htm"}
,{"title":"TSection.&amp;Type","href":"Casbin.Model.Sections.Types.TSection.&amp;Type.htm"}
,{"title":"TSection.EnforceTag","href":"Casbin.Model.Sections.Types.TSection.EnforceTag.htm"}
,{"title":"TSection.fEnforceTag","href":"Casbin.Model.Sections.Types.TSection.fEnforceTag.htm"}
,{"title":"TSection.fHeader","href":"Casbin.Model.Sections.Types.TSection.fHeader.htm"}
,{"title":"TSection.fRequired","href":"Casbin.Model.Sections.Types.TSection.fRequired.htm"}
,{"title":"TSection.fTag","href":"Casbin.Model.Sections.Types.TSection.fTag.htm"}
,{"title":"TSection.fType","href":"Casbin.Model.Sections.Types.TSection.fType.htm"}
,{"title":"TSection.Header","href":"Casbin.Model.Sections.Types.TSection.Header.htm"}
,{"title":"TSection.Required","href":"Casbin.Model.Sections.Types.TSection.Required.htm"}
,{"title":"TSection.Tag","href":"Casbin.Model.Sections.Types.TSection.Tag.htm"}
,{"title":"TSectionDefault","href":"Casbin.Model.Sections.Default.TSectionDefault.htm"}
,{"title":"TSectionDefault.Header","href":"Casbin.Model.Sections.Default.TSectionDefault.Header.htm"}
,{"title":"TSectionDefault.Tag","href":"Casbin.Model.Sections.Default.TSectionDefault.Tag.htm"}
,{"title":"TSectionType","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stDefault","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stMatchers","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stPolicyDefinition","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stPolicyEffect","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stPolicyRules","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stRequestDefinition","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stRoleDefinition","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionType.stUnknown","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
,{"title":"TSectionTypeSet","href":"Casbin.Model.Sections.Types.TSectionTypeSet.htm"}
,{"title":"TSimpleStringFunction","href":"ParseClass.TSimpleStringFunction.htm"}
,{"title":"TSimpleStringFunction.Create(string,string,TStringFunc,TExprWord,TExprWord)","href":"ParseClass.TSimpleStringFunction.Create.htm"}
,{"title":"TSimpleStringFunction.Evaluate","href":"ParseClass.TSimpleStringFunction.Evaluate.htm"}
,{"title":"TSimpleStringFunction.FLeftArg","href":"ParseClass.TSimpleStringFunction.FLeftArg.htm"}
,{"title":"TSimpleStringFunction.FRightArg","href":"ParseClass.TSimpleStringFunction.FRightArg.htm"}
,{"title":"TSimpleStringFunction.FStringFunc","href":"ParseClass.TSimpleStringFunction.FStringFunc.htm"}
,{"title":"TSimpleStringFunction.GetCanVary","href":"ParseClass.TSimpleStringFunction.GetCanVary.htm"}
,{"title":"TSimpleStringFunction.StringFunc","href":"ParseClass.TSimpleStringFunction.StringFunc.htm"}
,{"title":"TSortedCollection","href":"OObjects.TSortedCollection.htm"}
,{"title":"TSortedCollection.Add(Pointer)","href":"OObjects.TSortedCollection.Add.htm"}
,{"title":"TSortedCollection.AddReplace(Pointer)","href":"OObjects.TSortedCollection.AddReplace.htm"}
,{"title":"TSortedCollection.Compare(Pointer,Pointer)","href":"OObjects.TSortedCollection.Compare.htm"}
,{"title":"TSortedCollection.Create(Integer)","href":"OObjects.TSortedCollection.Create.htm"}
,{"title":"TSortedCollection.Duplicates","href":"OObjects.TSortedCollection.Duplicates.htm"}
,{"title":"TSortedCollection.IndexOf(Pointer)","href":"OObjects.TSortedCollection.IndexOf.htm"}
,{"title":"TSortedCollection.KeyOf(Pointer)","href":"OObjects.TSortedCollection.KeyOf.htm"}
,{"title":"TSortedCollection.Search(Pointer,Integer)","href":"OObjects.TSortedCollection.Search.htm"}
,{"title":"TStrCollection","href":"OObjects.TStrCollection.htm"}
,{"title":"TStrCollection.Compare(Pointer,Pointer)","href":"OObjects.TStrCollection.Compare.htm"}
,{"title":"TStrCollection.FreeItem(Pointer)","href":"OObjects.TStrCollection.FreeItem.htm"}
,{"title":"TStringConstant","href":"ParseClass.TStringConstant.htm"}
,{"title":"TStringConstant.Create(string)","href":"ParseClass.TStringConstant.Create.htm"}
,{"title":"TStringConstant.FValue","href":"ParseClass.TStringConstant.FValue.htm"}
,{"title":"TStringConstant.GetAsString","href":"ParseClass.TStringConstant.GetAsString.htm"}
,{"title":"TStringConstant.GetVarType","href":"ParseClass.TStringConstant.GetVarType.htm"}
,{"title":"TStringFunc","href":"ParseClass.TStringFunc.htm"}
,{"title":"TStringVariable","href":"ParseClass.TStringVariable.htm"}
,{"title":"TStringVariable.Create(string,PString)","href":"ParseClass.TStringVariable.Create.htm"}
,{"title":"TStringVariable.FValue","href":"ParseClass.TStringVariable.FValue.htm"}
,{"title":"TStringVariable.GetAsString","href":"ParseClass.TStringVariable.GetAsString.htm"}
,{"title":"TStringVariable.GetCanVary","href":"ParseClass.TStringVariable.GetCanVary.htm"}
,{"title":"TStringVariable.GetVarType","href":"ParseClass.TStringVariable.GetVarType.htm"}
,{"title":"TVarType","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtBoolean","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtComma","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtDouble","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtLeftBracket","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtRightBracket","href":"ParseClass.TVarType.htm"}
,{"title":"TVarType.vtString","href":"ParseClass.TVarType.htm"}
,{"title":"TVaryingFunction","href":"ParseClass.TVaryingFunction.htm"}
,{"title":"TVaryingFunction.GetCanVary","href":"ParseClass.TVaryingFunction.GetCanVary.htm"}
,{"title":"TVaryingStringFunction","href":"ParseClass.TVaryingStringFunction.htm"}
,{"title":"TVaryingStringFunction.GetCanVary","href":"ParseClass.TVaryingStringFunction.GetCanVary.htm"}
]