[{"title":"CasbinD103Rio","key":"CasbinD103Rio","href":"CasbinD103Rio.htm","activate":true,"children":[{"title":"Casbin.Adapter.Base","key":"Casbin.Adapter.Base","href":"Casbin.Adapter.Base.htm","children":[{"title":"Classes","key":"Casbin.Adapter.Base_Classes","href":"Casbin.Adapter.Base_Classes.htm","children":[{"title":"TBaseAdapter","key":"Casbin.Adapter.Base.TBaseAdapter","href":"Casbin.Adapter.Base.TBaseAdapter.htm","children":[{"title":"Constructors","key":"Casbin.Adapter.Base.TBaseAdapter_Constructors","href":"Casbin.Adapter.Base.TBaseAdapter_Constructors.htm","children":[{"title":"Create","key":"Casbin.Adapter.Base.TBaseAdapter.Create","href":"Casbin.Adapter.Base.TBaseAdapter.Create.htm"}
,{"title":"Destroy","key":"Casbin.Adapter.Base.TBaseAdapter.Destroy","href":"Casbin.Adapter.Base.TBaseAdapter.Destroy.htm"}
]}
,{"title":"Methods","key":"Casbin.Adapter.Base.TBaseAdapter_Methods","href":"Casbin.Adapter.Base.TBaseAdapter_Methods.htm","children":[{"title":"clear","key":"Casbin.Adapter.Base.TBaseAdapter.clear","href":"Casbin.Adapter.Base.TBaseAdapter.clear.htm"}
,{"title":"getAssertions","key":"Casbin.Adapter.Base.TBaseAdapter.getAssertions","href":"Casbin.Adapter.Base.TBaseAdapter.getAssertions.htm"}
,{"title":"getFilter","key":"Casbin.Adapter.Base.TBaseAdapter.getFilter","href":"Casbin.Adapter.Base.TBaseAdapter.getFilter.htm"}
,{"title":"getFiltered","key":"Casbin.Adapter.Base.TBaseAdapter.getFiltered","href":"Casbin.Adapter.Base.TBaseAdapter.getFiltered.htm"}
,{"title":"getLogger","key":"Casbin.Adapter.Base.TBaseAdapter.getLogger","href":"Casbin.Adapter.Base.TBaseAdapter.getLogger.htm"}
,{"title":"load(TFilterArray)","key":"Casbin.Adapter.Base.TBaseAdapter.load(TFilterArray)","href":"Casbin.Adapter.Base.TBaseAdapter.load.htm"}
,{"title":"save","key":"Casbin.Adapter.Base.TBaseAdapter.save","href":"Casbin.Adapter.Base.TBaseAdapter.save.htm"}
,{"title":"setAssertions(TList)","key":"Casbin.Adapter.Base.TBaseAdapter.setAssertions(TList)","href":"Casbin.Adapter.Base.TBaseAdapter.setAssertions.htm"}
,{"title":"setLogger(ILogger)","key":"Casbin.Adapter.Base.TBaseAdapter.setLogger(ILogger)","href":"Casbin.Adapter.Base.TBaseAdapter.setLogger.htm"}
,{"title":"toOutputString","key":"Casbin.Adapter.Base.TBaseAdapter.toOutputString","href":"Casbin.Adapter.Base.TBaseAdapter.toOutputString.htm"}
]}
,{"title":"Fields","key":"Casbin.Adapter.Base.TBaseAdapter_Fields","href":"Casbin.Adapter.Base.TBaseAdapter_Fields.htm","children":[{"title":"fAssertions","key":"Casbin.Adapter.Base.TBaseAdapter.fAssertions","href":"Casbin.Adapter.Base.TBaseAdapter.fAssertions.htm"}
,{"title":"fFilter","key":"Casbin.Adapter.Base.TBaseAdapter.fFilter","href":"Casbin.Adapter.Base.TBaseAdapter.fFilter.htm"}
,{"title":"fFiltered","key":"Casbin.Adapter.Base.TBaseAdapter.fFiltered","href":"Casbin.Adapter.Base.TBaseAdapter.fFiltered.htm"}
,{"title":"fLogger","key":"Casbin.Adapter.Base.TBaseAdapter.fLogger","href":"Casbin.Adapter.Base.TBaseAdapter.fLogger.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Adapter.Filesystem","key":"Casbin.Adapter.Filesystem","href":"Casbin.Adapter.Filesystem.htm","children":[{"title":"Classes","key":"Casbin.Adapter.Filesystem_Classes","href":"Casbin.Adapter.Filesystem_Classes.htm","children":[{"title":"TFileAdapter","key":"Casbin.Adapter.Filesystem.TFileAdapter","href":"Casbin.Adapter.Filesystem.TFileAdapter.htm","children":[{"title":"Constructors","key":"Casbin.Adapter.Filesystem.TFileAdapter_Constructors","href":"Casbin.Adapter.Filesystem.TFileAdapter_Constructors.htm","children":[{"title":"Create(string)","key":"Casbin.Adapter.Filesystem.TFileAdapter.Create(string)","href":"Casbin.Adapter.Filesystem.TFileAdapter.Create.htm"}
]}
,{"title":"Methods","key":"Casbin.Adapter.Filesystem.TFileAdapter_Methods","href":"Casbin.Adapter.Filesystem.TFileAdapter_Methods.htm","children":[{"title":"load(TFilterArray)","key":"Casbin.Adapter.Filesystem.TFileAdapter.load(TFilterArray)","href":"Casbin.Adapter.Filesystem.TFileAdapter.load.htm"}
,{"title":"save","key":"Casbin.Adapter.Filesystem.TFileAdapter.save","href":"Casbin.Adapter.Filesystem.TFileAdapter.save.htm"}
]}
,{"title":"Fields","key":"Casbin.Adapter.Filesystem.TFileAdapter_Fields","href":"Casbin.Adapter.Filesystem.TFileAdapter_Fields.htm","children":[{"title":"fFilename","key":"Casbin.Adapter.Filesystem.TFileAdapter.fFilename","href":"Casbin.Adapter.Filesystem.TFileAdapter.fFilename.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Adapter.Filesystem.Policy","key":"Casbin.Adapter.Filesystem.Policy","href":"Casbin.Adapter.Filesystem.Policy.htm","children":[{"title":"Classes","key":"Casbin.Adapter.Filesystem.Policy_Classes","href":"Casbin.Adapter.Filesystem.Policy_Classes.htm","children":[{"title":"TPolicyFileAdapter","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.htm","children":[{"title":"Constructors","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Constructors","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Constructors.htm","children":[{"title":"Create(string)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.Create(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.Create.htm"}
]}
,{"title":"Methods","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Methods","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Methods.htm","children":[{"title":"add(string)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.add(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.add.htm"}
,{"title":"getAutoSave","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getAutoSave","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getAutoSave.htm"}
,{"title":"getCached","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCached","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCached.htm"}
,{"title":"getCacheSize","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCacheSize","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.getCacheSize.htm"}
,{"title":"load(TFilterArray)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.load(TFilterArray)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.load.htm"}
,{"title":"remove(string)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string).htm"}
,{"title":"remove(string,string)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string,string)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.remove(string,string).htm"}
,{"title":"save","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.save","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.save.htm"}
,{"title":"setAutoSave(Boolean)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setAutoSave(Boolean)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setAutoSave.htm"}
,{"title":"setCached(Boolean)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCached(Boolean)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCached.htm"}
,{"title":"setCacheSize(Integer)","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCacheSize(Integer)","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.setCacheSize.htm"}
]}
,{"title":"Fields","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Fields","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter_Fields.htm","children":[{"title":"fAutosave","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fAutosave","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fAutosave.htm"}
,{"title":"fCached","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCached","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCached.htm"}
,{"title":"fCacheSize","key":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCacheSize","href":"Casbin.Adapter.Filesystem.Policy.TPolicyFileAdapter.fCacheSize.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Adapter.Policy.Types","key":"Casbin.Adapter.Policy.Types","href":"Casbin.Adapter.Policy.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Adapter.Policy.Types_Interfaces","href":"Casbin.Adapter.Policy.Types_Interfaces.htm","children":[{"title":"IPolicyAdapter","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.htm","children":[{"title":"Properties","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter_Properties","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter_Properties.htm","children":[{"title":"AutoSave","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.AutoSave","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.AutoSave.htm"}
,{"title":"Cached","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.Cached","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.Cached.htm"}
,{"title":"CacheSize","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.CacheSize","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.CacheSize.htm"}
]}
,{"title":"Methods","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter_Methods","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter_Methods.htm","children":[{"title":"add(string)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.add(string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.add.htm"}
,{"title":"getAutoSave","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getAutoSave","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getAutoSave.htm"}
,{"title":"getCached","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCached","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCached.htm"}
,{"title":"getCacheSize","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCacheSize","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.getCacheSize.htm"}
,{"title":"remove(string)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string).htm"}
,{"title":"remove(string,string)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string,string)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.remove(string,string).htm"}
,{"title":"setAutoSave(Boolean)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setAutoSave(Boolean)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setAutoSave.htm"}
,{"title":"setCached(boolean)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCached(boolean)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCached.htm"}
,{"title":"setCacheSize(Integer)","key":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCacheSize(Integer)","href":"Casbin.Adapter.Policy.Types.IPolicyAdapter.setCacheSize.htm"}
]}
]}
]}
,{"title":"Constants","key":"Casbin.Adapter.Policy.Types_Constants","href":"Casbin.Adapter.Policy.Types_Constants.htm","children":[{"title":"DefaultCacheSize","key":"Casbin.Adapter.Policy.Types.DefaultCacheSize","href":"Casbin.Adapter.Policy.Types.DefaultCacheSize.htm"}
]}
]}
,{"title":"Casbin.Adapter.Types","key":"Casbin.Adapter.Types","href":"Casbin.Adapter.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Adapter.Types_Interfaces","href":"Casbin.Adapter.Types_Interfaces.htm","children":[{"title":"IAdapter","key":"Casbin.Adapter.Types.IAdapter","href":"Casbin.Adapter.Types.IAdapter.htm","children":[{"title":"Properties","key":"Casbin.Adapter.Types.IAdapter_Properties","href":"Casbin.Adapter.Types.IAdapter_Properties.htm","children":[{"title":"Assertions","key":"Casbin.Adapter.Types.IAdapter.Assertions","href":"Casbin.Adapter.Types.IAdapter.Assertions.htm"}
,{"title":"Filter","key":"Casbin.Adapter.Types.IAdapter.Filter","href":"Casbin.Adapter.Types.IAdapter.Filter.htm"}
,{"title":"Filtered","key":"Casbin.Adapter.Types.IAdapter.Filtered","href":"Casbin.Adapter.Types.IAdapter.Filtered.htm"}
,{"title":"Logger","key":"Casbin.Adapter.Types.IAdapter.Logger","href":"Casbin.Adapter.Types.IAdapter.Logger.htm"}
]}
,{"title":"Methods","key":"Casbin.Adapter.Types.IAdapter_Methods","href":"Casbin.Adapter.Types.IAdapter_Methods.htm","children":[{"title":"clear","key":"Casbin.Adapter.Types.IAdapter.clear","href":"Casbin.Adapter.Types.IAdapter.clear.htm"}
,{"title":"getAssertions","key":"Casbin.Adapter.Types.IAdapter.getAssertions","href":"Casbin.Adapter.Types.IAdapter.getAssertions.htm"}
,{"title":"getFilter","key":"Casbin.Adapter.Types.IAdapter.getFilter","href":"Casbin.Adapter.Types.IAdapter.getFilter.htm"}
,{"title":"getFiltered","key":"Casbin.Adapter.Types.IAdapter.getFiltered","href":"Casbin.Adapter.Types.IAdapter.getFiltered.htm"}
,{"title":"getLogger","key":"Casbin.Adapter.Types.IAdapter.getLogger","href":"Casbin.Adapter.Types.IAdapter.getLogger.htm"}
,{"title":"load(TFilterArray)","key":"Casbin.Adapter.Types.IAdapter.load(TFilterArray)","href":"Casbin.Adapter.Types.IAdapter.load.htm"}
,{"title":"save","key":"Casbin.Adapter.Types.IAdapter.save","href":"Casbin.Adapter.Types.IAdapter.save.htm"}
,{"title":"setAssertions(TList)","key":"Casbin.Adapter.Types.IAdapter.setAssertions(TList)","href":"Casbin.Adapter.Types.IAdapter.setAssertions.htm"}
,{"title":"setLogger(ILogger)","key":"Casbin.Adapter.Types.IAdapter.setLogger(ILogger)","href":"Casbin.Adapter.Types.IAdapter.setLogger.htm"}
,{"title":"toOutputString","key":"Casbin.Adapter.Types.IAdapter.toOutputString","href":"Casbin.Adapter.Types.IAdapter.toOutputString.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Core.Base.Types","key":"Casbin.Core.Base.Types","href":"Casbin.Core.Base.Types.htm","children":[{"title":"Classes","key":"Casbin.Core.Base.Types_Classes","href":"Casbin.Core.Base.Types_Classes.htm","children":[{"title":"TBaseInterfacedObject","key":"Casbin.Core.Base.Types.TBaseInterfacedObject","href":"Casbin.Core.Base.Types.TBaseInterfacedObject.htm"}
,{"title":"TBaseObject","key":"Casbin.Core.Base.Types.TBaseObject","href":"Casbin.Core.Base.Types.TBaseObject.htm"}
]}
,{"title":"Interfaces","key":"Casbin.Core.Base.Types_Interfaces","href":"Casbin.Core.Base.Types_Interfaces.htm","children":[{"title":"IBaseInterface","key":"Casbin.Core.Base.Types.IBaseInterface","href":"Casbin.Core.Base.Types.IBaseInterface.htm"}
]}
,{"title":"Types","key":"Casbin.Core.Base.Types_Types","href":"Casbin.Core.Base.Types_Types.htm","children":[{"title":"TFilterArray","key":"Casbin.Core.Base.Types.TFilterArray","href":"Casbin.Core.Base.Types.TFilterArray.htm"}
]}
]}
,{"title":"Casbin.Core.Defaults","key":"Casbin.Core.Defaults","href":"Casbin.Core.Defaults.htm","children":[{"title":"Constants","key":"Casbin.Core.Defaults_Constants","href":"Casbin.Core.Defaults_Constants.htm","children":[{"title":"AssignmentCharForConfig","key":"Casbin.Core.Defaults.AssignmentCharForConfig","href":"Casbin.Core.Defaults.AssignmentCharForConfig.htm"}
,{"title":"AssignmentCharForModel","key":"Casbin.Core.Defaults.AssignmentCharForModel","href":"Casbin.Core.Defaults.AssignmentCharForModel.htm"}
,{"title":"AssignmentCharForPolicies","key":"Casbin.Core.Defaults.AssignmentCharForPolicies","href":"Casbin.Core.Defaults.AssignmentCharForPolicies.htm"}
,{"title":"DefaultCommentCharacters","key":"Casbin.Core.Defaults.DefaultCommentCharacters","href":"Casbin.Core.Defaults.DefaultCommentCharacters.htm"}
,{"title":"DefaultMultilineCharacters","key":"Casbin.Core.Defaults.DefaultMultilineCharacters","href":"Casbin.Core.Defaults.DefaultMultilineCharacters.htm"}
,{"title":"DefaultSection","key":"Casbin.Core.Defaults.DefaultSection","href":"Casbin.Core.Defaults.DefaultSection.htm"}
,{"title":"EOL","key":"Casbin.Core.Defaults.EOL","href":"Casbin.Core.Defaults.EOL.htm"}
]}
]}
,{"title":"Casbin.Core.Logger.Base","key":"Casbin.Core.Logger.Base","href":"Casbin.Core.Logger.Base.htm","children":[{"title":"Classes","key":"Casbin.Core.Logger.Base_Classes","href":"Casbin.Core.Logger.Base_Classes.htm","children":[{"title":"TBaseLogger","key":"Casbin.Core.Logger.Base.TBaseLogger","href":"Casbin.Core.Logger.Base.TBaseLogger.htm","children":[{"title":"Constructors","key":"Casbin.Core.Logger.Base.TBaseLogger_Constructors","href":"Casbin.Core.Logger.Base.TBaseLogger_Constructors.htm","children":[{"title":"Create","key":"Casbin.Core.Logger.Base.TBaseLogger.Create","href":"Casbin.Core.Logger.Base.TBaseLogger.Create.htm"}
]}
,{"title":"Methods","key":"Casbin.Core.Logger.Base.TBaseLogger_Methods","href":"Casbin.Core.Logger.Base.TBaseLogger_Methods.htm","children":[{"title":"getEnabled","key":"Casbin.Core.Logger.Base.TBaseLogger.getEnabled","href":"Casbin.Core.Logger.Base.TBaseLogger.getEnabled.htm"}
,{"title":"getLastLoggedMessage","key":"Casbin.Core.Logger.Base.TBaseLogger.getLastLoggedMessage","href":"Casbin.Core.Logger.Base.TBaseLogger.getLastLoggedMessage.htm"}
,{"title":"log(string)","key":"Casbin.Core.Logger.Base.TBaseLogger.log(string)","href":"Casbin.Core.Logger.Base.TBaseLogger.log.htm"}
,{"title":"setEnabled(Boolean)","key":"Casbin.Core.Logger.Base.TBaseLogger.setEnabled(Boolean)","href":"Casbin.Core.Logger.Base.TBaseLogger.setEnabled.htm"}
]}
,{"title":"Fields","key":"Casbin.Core.Logger.Base.TBaseLogger_Fields","href":"Casbin.Core.Logger.Base.TBaseLogger_Fields.htm","children":[{"title":"fEnabled","key":"Casbin.Core.Logger.Base.TBaseLogger.fEnabled","href":"Casbin.Core.Logger.Base.TBaseLogger.fEnabled.htm"}
,{"title":"fLastLoggedMessage","key":"Casbin.Core.Logger.Base.TBaseLogger.fLastLoggedMessage","href":"Casbin.Core.Logger.Base.TBaseLogger.fLastLoggedMessage.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Core.Logger.Default","key":"Casbin.Core.Logger.Default","href":"Casbin.Core.Logger.Default.htm","children":[{"title":"Classes","key":"Casbin.Core.Logger.Default_Classes","href":"Casbin.Core.Logger.Default_Classes.htm","children":[{"title":"TDefaultLogger","key":"Casbin.Core.Logger.Default.TDefaultLogger","href":"Casbin.Core.Logger.Default.TDefaultLogger.htm","children":[{"title":"Methods","key":"Casbin.Core.Logger.Default.TDefaultLogger_Methods","href":"Casbin.Core.Logger.Default.TDefaultLogger_Methods.htm","children":[{"title":"log(string)","key":"Casbin.Core.Logger.Default.TDefaultLogger.log(string)","href":"Casbin.Core.Logger.Default.TDefaultLogger.log.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Core.Logger.Types","key":"Casbin.Core.Logger.Types","href":"Casbin.Core.Logger.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Core.Logger.Types_Interfaces","href":"Casbin.Core.Logger.Types_Interfaces.htm","children":[{"title":"ILogger","key":"Casbin.Core.Logger.Types.ILogger","href":"Casbin.Core.Logger.Types.ILogger.htm","children":[{"title":"Properties","key":"Casbin.Core.Logger.Types.ILogger_Properties","href":"Casbin.Core.Logger.Types.ILogger_Properties.htm","children":[{"title":"Enabled","key":"Casbin.Core.Logger.Types.ILogger.Enabled","href":"Casbin.Core.Logger.Types.ILogger.Enabled.htm"}
,{"title":"LastLoggedMessage","key":"Casbin.Core.Logger.Types.ILogger.LastLoggedMessage","href":"Casbin.Core.Logger.Types.ILogger.LastLoggedMessage.htm"}
]}
,{"title":"Methods","key":"Casbin.Core.Logger.Types.ILogger_Methods","href":"Casbin.Core.Logger.Types.ILogger_Methods.htm","children":[{"title":"getEnabled","key":"Casbin.Core.Logger.Types.ILogger.getEnabled","href":"Casbin.Core.Logger.Types.ILogger.getEnabled.htm"}
,{"title":"getLastLoggedMessage","key":"Casbin.Core.Logger.Types.ILogger.getLastLoggedMessage","href":"Casbin.Core.Logger.Types.ILogger.getLastLoggedMessage.htm"}
,{"title":"log(string)","key":"Casbin.Core.Logger.Types.ILogger.log(string)","href":"Casbin.Core.Logger.Types.ILogger.log.htm"}
,{"title":"setEnabled(Boolean)","key":"Casbin.Core.Logger.Types.ILogger.setEnabled(Boolean)","href":"Casbin.Core.Logger.Types.ILogger.setEnabled.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Core.Strings","key":"Casbin.Core.Strings","href":"Casbin.Core.Strings.htm","children":[{"title":"Constants","key":"Casbin.Core.Strings_Constants","href":"Casbin.Core.Strings_Constants.htm","children":[{"title":"configFileString","key":"Casbin.Core.Strings.configFileString","href":"Casbin.Core.Strings.configFileString.htm"}
,{"title":"errorSectionNotFound","key":"Casbin.Core.Strings.errorSectionNotFound","href":"Casbin.Core.Strings.errorSectionNotFound.htm"}
,{"title":"errorUnknownAssertion","key":"Casbin.Core.Strings.errorUnknownAssertion","href":"Casbin.Core.Strings.errorUnknownAssertion.htm"}
,{"title":"errorWrongHeaderFormat","key":"Casbin.Core.Strings.errorWrongHeaderFormat","href":"Casbin.Core.Strings.errorWrongHeaderFormat.htm"}
,{"title":"modelFileString","key":"Casbin.Core.Strings.modelFileString","href":"Casbin.Core.Strings.modelFileString.htm"}
,{"title":"policyFileString","key":"Casbin.Core.Strings.policyFileString","href":"Casbin.Core.Strings.policyFileString.htm"}
]}
]}
,{"title":"Casbin.Core.Utilities","key":"Casbin.Core.Utilities","href":"Casbin.Core.Utilities.htm","children":[{"title":"Routines","key":"Casbin.Core.Utilities_Routines","href":"Casbin.Core.Utilities_Routines.htm","children":[{"title":"findEndPos(string)","key":"Casbin.Core.Utilities.findEndPos(string)","href":"Casbin.Core.Utilities.findEndPos.htm"}
,{"title":"findStartPos","key":"Casbin.Core.Utilities.findStartPos","href":"Casbin.Core.Utilities.findStartPos.htm"}
]}
]}
,{"title":"Casbin.Effect","key":"Casbin.Effect","href":"Casbin.Effect.htm","children":[{"title":"Routines","key":"Casbin.Effect_Routines","href":"Casbin.Effect_Routines.htm","children":[{"title":"mergeEffects(TEffectCondition,TEffectArray)","key":"Casbin.Effect.mergeEffects(TEffectCondition,TEffectArray)","href":"Casbin.Effect.mergeEffects.htm"}
]}
]}
,{"title":"Casbin.Effect.Types","key":"Casbin.Effect.Types","href":"Casbin.Effect.Types.htm","children":[{"title":"Enumerations","key":"Casbin.Effect.Types_Enumerations","href":"Casbin.Effect.Types_Enumerations.htm","children":[{"title":"TEffectCondition","key":"Casbin.Effect.Types.TEffectCondition","href":"Casbin.Effect.Types.TEffectCondition.htm"}
,{"title":"TEffectResult","key":"Casbin.Effect.Types.TEffectResult","href":"Casbin.Effect.Types.TEffectResult.htm"}
]}
,{"title":"Types","key":"Casbin.Effect.Types_Types","href":"Casbin.Effect.Types_Types.htm","children":[{"title":"TEffectArray","key":"Casbin.Effect.Types.TEffectArray","href":"Casbin.Effect.Types.TEffectArray.htm"}
]}
,{"title":"Constants","key":"Casbin.Effect.Types_Constants","href":"Casbin.Effect.Types_Constants.htm","children":[{"title":"effectConditions","key":"Casbin.Effect.Types.effectConditions","href":"Casbin.Effect.Types.effectConditions.htm"}
]}
]}
,{"title":"Casbin.Exception.Types","key":"Casbin.Exception.Types","href":"Casbin.Exception.Types.htm","children":[{"title":"Classes","key":"Casbin.Exception.Types_Classes","href":"Casbin.Exception.Types_Classes.htm","children":[{"title":"ECasbinException","key":"Casbin.Exception.Types.ECasbinException","href":"Casbin.Exception.Types.ECasbinException.htm"}
]}
]}
,{"title":"Casbin.Functions","key":"Casbin.Functions","href":"Casbin.Functions.htm","children":[{"title":"Classes","key":"Casbin.Functions_Classes","href":"Casbin.Functions_Classes.htm","children":[{"title":"TFunctions","key":"Casbin.Functions.TFunctions","href":"Casbin.Functions.TFunctions.htm","children":[{"title":"Constructors","key":"Casbin.Functions.TFunctions_Constructors","href":"Casbin.Functions.TFunctions_Constructors.htm","children":[{"title":"Create","key":"Casbin.Functions.TFunctions.Create","href":"Casbin.Functions.TFunctions.Create.htm"}
,{"title":"Destroy","key":"Casbin.Functions.TFunctions.Destroy","href":"Casbin.Functions.TFunctions.Destroy.htm"}
]}
,{"title":"Methods","key":"Casbin.Functions.TFunctions_Methods","href":"Casbin.Functions.TFunctions_Methods.htm","children":[{"title":"list","key":"Casbin.Functions.TFunctions.list","href":"Casbin.Functions.TFunctions.list.htm"}
,{"title":"loadBuiltInFunctions","key":"Casbin.Functions.TFunctions.loadBuiltInFunctions","href":"Casbin.Functions.TFunctions.loadBuiltInFunctions.htm"}
,{"title":"loadCustomFunctions","key":"Casbin.Functions.TFunctions.loadCustomFunctions","href":"Casbin.Functions.TFunctions.loadCustomFunctions.htm"}
,{"title":"refreshFunctions","key":"Casbin.Functions.TFunctions.refreshFunctions","href":"Casbin.Functions.TFunctions.refreshFunctions.htm"}
,{"title":"registerFunction(string,TCasbinFunc)","key":"Casbin.Functions.TFunctions.registerFunction(string,TCasbinFunc)","href":"Casbin.Functions.TFunctions.registerFunction.htm"}
,{"title":"retrieveFunction(string)","key":"Casbin.Functions.TFunctions.retrieveFunction(string)","href":"Casbin.Functions.TFunctions.retrieveFunction.htm"}
]}
,{"title":"Fields","key":"Casbin.Functions.TFunctions_Fields","href":"Casbin.Functions.TFunctions_Fields.htm","children":[{"title":"fDictionary","key":"Casbin.Functions.TFunctions.fDictionary","href":"Casbin.Functions.TFunctions.fDictionary.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Functions.Types","key":"Casbin.Functions.Types","href":"Casbin.Functions.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Functions.Types_Interfaces","href":"Casbin.Functions.Types_Interfaces.htm","children":[{"title":"IFunctions","key":"Casbin.Functions.Types.IFunctions","href":"Casbin.Functions.Types.IFunctions.htm","children":[{"title":"Methods","key":"Casbin.Functions.Types.IFunctions_Methods","href":"Casbin.Functions.Types.IFunctions_Methods.htm","children":[{"title":"list","key":"Casbin.Functions.Types.IFunctions.list","href":"Casbin.Functions.Types.IFunctions.list.htm"}
,{"title":"refreshFunctions","key":"Casbin.Functions.Types.IFunctions.refreshFunctions","href":"Casbin.Functions.Types.IFunctions.refreshFunctions.htm"}
,{"title":"registerFunction(string,TCasbinFunc)","key":"Casbin.Functions.Types.IFunctions.registerFunction(string,TCasbinFunc)","href":"Casbin.Functions.Types.IFunctions.registerFunction.htm"}
,{"title":"retrieveFunction(string)","key":"Casbin.Functions.Types.IFunctions.retrieveFunction(string)","href":"Casbin.Functions.Types.IFunctions.retrieveFunction.htm"}
]}
]}
]}
,{"title":"Delegates","key":"Casbin.Functions.Types_Delegates","href":"Casbin.Functions.Types_Delegates.htm","children":[{"title":"TCasbinFunc","key":"Casbin.Functions.Types.TCasbinFunc","href":"Casbin.Functions.Types.TCasbinFunc.htm"}
]}
]}
,{"title":"Casbin.Matcher","key":"Casbin.Matcher","href":"Casbin.Matcher.htm","children":[{"title":"Classes","key":"Casbin.Matcher_Classes","href":"Casbin.Matcher_Classes.htm","children":[{"title":"TMatcher","key":"Casbin.Matcher.TMatcher","href":"Casbin.Matcher.TMatcher.htm","children":[{"title":"Constructors","key":"Casbin.Matcher.TMatcher_Constructors","href":"Casbin.Matcher.TMatcher_Constructors.htm","children":[{"title":"Create","key":"Casbin.Matcher.TMatcher.Create","href":"Casbin.Matcher.TMatcher.Create.htm"}
,{"title":"Destroy","key":"Casbin.Matcher.TMatcher.Destroy","href":"Casbin.Matcher.TMatcher.Destroy.htm"}
]}
,{"title":"Methods","key":"Casbin.Matcher.TMatcher_Methods","href":"Casbin.Matcher.TMatcher_Methods.htm","children":[{"title":"cleanMatcher","key":"Casbin.Matcher.TMatcher.cleanMatcher","href":"Casbin.Matcher.TMatcher.cleanMatcher.htm"}
,{"title":"evaluateMatcher(string)","key":"Casbin.Matcher.TMatcher.evaluateMatcher(string)","href":"Casbin.Matcher.TMatcher.evaluateMatcher.htm"}
]}
,{"title":"Fields","key":"Casbin.Matcher.TMatcher_Fields","href":"Casbin.Matcher.TMatcher_Fields.htm","children":[{"title":"fMatcherString","key":"Casbin.Matcher.TMatcher.fMatcherString","href":"Casbin.Matcher.TMatcher.fMatcherString.htm"}
,{"title":"fMathsParser","key":"Casbin.Matcher.TMatcher.fMathsParser","href":"Casbin.Matcher.TMatcher.fMathsParser.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Matcher.Types","key":"Casbin.Matcher.Types","href":"Casbin.Matcher.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Matcher.Types_Interfaces","href":"Casbin.Matcher.Types_Interfaces.htm","children":[{"title":"IMatcher","key":"Casbin.Matcher.Types.IMatcher","href":"Casbin.Matcher.Types.IMatcher.htm","children":[{"title":"Methods","key":"Casbin.Matcher.Types.IMatcher_Methods","href":"Casbin.Matcher.Types.IMatcher_Methods.htm","children":[{"title":"evaluateMatcher(string)","key":"Casbin.Matcher.Types.IMatcher.evaluateMatcher(string)","href":"Casbin.Matcher.Types.IMatcher.evaluateMatcher.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Model","key":"Casbin.Model","href":"Casbin.Model.htm","children":[{"title":"Classes","key":"Casbin.Model_Classes","href":"Casbin.Model_Classes.htm","children":[{"title":"TModel","key":"Casbin.Model.TModel","href":"Casbin.Model.TModel.htm","children":[{"title":"Constructors","key":"Casbin.Model.TModel_Constructors","href":"Casbin.Model.TModel_Constructors.htm","children":[{"title":"Create(IAdapter)","key":"Casbin.Model.TModel.Create(IAdapter)","href":"Casbin.Model.TModel.Create(IAdapter).htm"}
,{"title":"Create(string)","key":"Casbin.Model.TModel.Create(string)","href":"Casbin.Model.TModel.Create(string).htm"}
]}
,{"title":"Methods","key":"Casbin.Model.TModel_Methods","href":"Casbin.Model.TModel_Methods.htm","children":[{"title":"assertions(TSectionType)","key":"Casbin.Model.TModel.assertions(TSectionType)","href":"Casbin.Model.TModel.assertions.htm"}
,{"title":"checkSection(TSectionType)","key":"Casbin.Model.TModel.checkSection(TSectionType)","href":"Casbin.Model.TModel.checkSection.htm"}
,{"title":"section(TSectionType,Boolean)","key":"Casbin.Model.TModel.section(TSectionType,Boolean)","href":"Casbin.Model.TModel.section.htm"}
]}
,{"title":"Fields","key":"Casbin.Model.TModel_Fields","href":"Casbin.Model.TModel_Fields.htm","children":[{"title":"fAdapter","key":"Casbin.Model.TModel.fAdapter","href":"Casbin.Model.TModel.fAdapter.htm"}
,{"title":"fNodes","key":"Casbin.Model.TModel.fNodes","href":"Casbin.Model.TModel.fNodes.htm"}
,{"title":"fParser","key":"Casbin.Model.TModel.fParser","href":"Casbin.Model.TModel.fParser.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Model.Sections.Default","key":"Casbin.Model.Sections.Default","href":"Casbin.Model.Sections.Default.htm","children":[{"title":"Records","key":"Casbin.Model.Sections.Default_Records","href":"Casbin.Model.Sections.Default_Records.htm","children":[{"title":"TSectionDefault","key":"Casbin.Model.Sections.Default.TSectionDefault","href":"Casbin.Model.Sections.Default.TSectionDefault.htm","children":[{"title":"Fields","key":"Casbin.Model.Sections.Default.TSectionDefault_Fields","href":"Casbin.Model.Sections.Default.TSectionDefault_Fields.htm","children":[{"title":"Header","key":"Casbin.Model.Sections.Default.TSectionDefault.Header","href":"Casbin.Model.Sections.Default.TSectionDefault.Header.htm"}
,{"title":"Tag","key":"Casbin.Model.Sections.Default.TSectionDefault.Tag","href":"Casbin.Model.Sections.Default.TSectionDefault.Tag.htm"}
]}
]}
]}
,{"title":"Constants","key":"Casbin.Model.Sections.Default_Constants","href":"Casbin.Model.Sections.Default_Constants.htm","children":[{"title":"defaultSection","key":"Casbin.Model.Sections.Default.defaultSection","href":"Casbin.Model.Sections.Default.defaultSection.htm"}
,{"title":"matchersDefinition","key":"Casbin.Model.Sections.Default.matchersDefinition","href":"Casbin.Model.Sections.Default.matchersDefinition.htm"}
,{"title":"policyDefinition","key":"Casbin.Model.Sections.Default.policyDefinition","href":"Casbin.Model.Sections.Default.policyDefinition.htm"}
,{"title":"policyEffectDefinition","key":"Casbin.Model.Sections.Default.policyEffectDefinition","href":"Casbin.Model.Sections.Default.policyEffectDefinition.htm"}
,{"title":"requestDefinition","key":"Casbin.Model.Sections.Default.requestDefinition","href":"Casbin.Model.Sections.Default.requestDefinition.htm"}
,{"title":"roleDefinition","key":"Casbin.Model.Sections.Default.roleDefinition","href":"Casbin.Model.Sections.Default.roleDefinition.htm"}
]}
,{"title":"Routines","key":"Casbin.Model.Sections.Default_Routines","href":"Casbin.Model.Sections.Default_Routines.htm","children":[{"title":"createDefaultSection(TSectionType)","key":"Casbin.Model.Sections.Default.createDefaultSection(TSectionType)","href":"Casbin.Model.Sections.Default.createDefaultSection.htm"}
]}
]}
,{"title":"Casbin.Model.Sections.Types","key":"Casbin.Model.Sections.Types","href":"Casbin.Model.Sections.Types.htm","children":[{"title":"Classes","key":"Casbin.Model.Sections.Types_Classes","href":"Casbin.Model.Sections.Types_Classes.htm","children":[{"title":"TSection","key":"Casbin.Model.Sections.Types.TSection","href":"Casbin.Model.Sections.Types.TSection.htm","children":[{"title":"Properties","key":"Casbin.Model.Sections.Types.TSection_Properties","href":"Casbin.Model.Sections.Types.TSection_Properties.htm","children":[{"title":"&amp;Type","key":"Casbin.Model.Sections.Types.TSection.&amp;Type","href":"Casbin.Model.Sections.Types.TSection.&amp;Type.htm"}
,{"title":"EnforceTag","key":"Casbin.Model.Sections.Types.TSection.EnforceTag","href":"Casbin.Model.Sections.Types.TSection.EnforceTag.htm"}
,{"title":"Header","key":"Casbin.Model.Sections.Types.TSection.Header","href":"Casbin.Model.Sections.Types.TSection.Header.htm"}
,{"title":"Required","key":"Casbin.Model.Sections.Types.TSection.Required","href":"Casbin.Model.Sections.Types.TSection.Required.htm"}
,{"title":"Tag","key":"Casbin.Model.Sections.Types.TSection.Tag","href":"Casbin.Model.Sections.Types.TSection.Tag.htm"}
]}
,{"title":"Fields","key":"Casbin.Model.Sections.Types.TSection_Fields","href":"Casbin.Model.Sections.Types.TSection_Fields.htm","children":[{"title":"fEnforceTag","key":"Casbin.Model.Sections.Types.TSection.fEnforceTag","href":"Casbin.Model.Sections.Types.TSection.fEnforceTag.htm"}
,{"title":"fHeader","key":"Casbin.Model.Sections.Types.TSection.fHeader","href":"Casbin.Model.Sections.Types.TSection.fHeader.htm"}
,{"title":"fRequired","key":"Casbin.Model.Sections.Types.TSection.fRequired","href":"Casbin.Model.Sections.Types.TSection.fRequired.htm"}
,{"title":"fTag","key":"Casbin.Model.Sections.Types.TSection.fTag","href":"Casbin.Model.Sections.Types.TSection.fTag.htm"}
,{"title":"fType","key":"Casbin.Model.Sections.Types.TSection.fType","href":"Casbin.Model.Sections.Types.TSection.fType.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"Casbin.Model.Sections.Types_Enumerations","href":"Casbin.Model.Sections.Types_Enumerations.htm","children":[{"title":"TSectionType","key":"Casbin.Model.Sections.Types.TSectionType","href":"Casbin.Model.Sections.Types.TSectionType.htm"}
]}
,{"title":"Types","key":"Casbin.Model.Sections.Types_Types","href":"Casbin.Model.Sections.Types_Types.htm","children":[{"title":"TSectionTypeSet","key":"Casbin.Model.Sections.Types.TSectionTypeSet","href":"Casbin.Model.Sections.Types.TSectionTypeSet.htm"}
]}
,{"title":"Constants","key":"Casbin.Model.Sections.Types_Constants","href":"Casbin.Model.Sections.Types_Constants.htm","children":[{"title":"congigSections","key":"Casbin.Model.Sections.Types.congigSections","href":"Casbin.Model.Sections.Types.congigSections.htm"}
,{"title":"modelSections","key":"Casbin.Model.Sections.Types.modelSections","href":"Casbin.Model.Sections.Types.modelSections.htm"}
,{"title":"policySections","key":"Casbin.Model.Sections.Types.policySections","href":"Casbin.Model.Sections.Types.policySections.htm"}
]}
]}
,{"title":"Casbin.Model.Types","key":"Casbin.Model.Types","href":"Casbin.Model.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Model.Types_Interfaces","href":"Casbin.Model.Types_Interfaces.htm","children":[{"title":"IModel","key":"Casbin.Model.Types.IModel","href":"Casbin.Model.Types.IModel.htm","children":[{"title":"Methods","key":"Casbin.Model.Types.IModel_Methods","href":"Casbin.Model.Types.IModel_Methods.htm","children":[{"title":"assertions(TSectionType)","key":"Casbin.Model.Types.IModel.assertions(TSectionType)","href":"Casbin.Model.Types.IModel.assertions.htm"}
,{"title":"section(TSectionType,Boolean)","key":"Casbin.Model.Types.IModel.section(TSectionType,Boolean)","href":"Casbin.Model.Types.IModel.section.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Parser","key":"Casbin.Parser","href":"Casbin.Parser.htm","children":[{"title":"Classes","key":"Casbin.Parser_Classes","href":"Casbin.Parser_Classes.htm","children":[{"title":"TParser","key":"Casbin.Parser.TParser","href":"Casbin.Parser.TParser.htm","children":[{"title":"Constructors","key":"Casbin.Parser.TParser_Constructors","href":"Casbin.Parser.TParser_Constructors.htm","children":[{"title":"Create(string,TParseType)","key":"Casbin.Parser.TParser.Create(string,TParseType)","href":"Casbin.Parser.TParser.Create.htm"}
,{"title":"Destroy","key":"Casbin.Parser.TParser.Destroy","href":"Casbin.Parser.TParser.Destroy.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.TParser_Methods","href":"Casbin.Parser.TParser_Methods.htm","children":[{"title":"checkHeaders","key":"Casbin.Parser.TParser.checkHeaders","href":"Casbin.Parser.TParser.checkHeaders.htm"}
,{"title":"checkSyntaxErrors","key":"Casbin.Parser.TParser.checkSyntaxErrors","href":"Casbin.Parser.TParser.checkSyntaxErrors.htm"}
,{"title":"cleanWhiteSpace","key":"Casbin.Parser.TParser.cleanWhiteSpace","href":"Casbin.Parser.TParser.cleanWhiteSpace.htm"}
,{"title":"getErrorMessage","key":"Casbin.Parser.TParser.getErrorMessage","href":"Casbin.Parser.TParser.getErrorMessage.htm"}
,{"title":"getLogger","key":"Casbin.Parser.TParser.getLogger","href":"Casbin.Parser.TParser.getLogger.htm"}
,{"title":"getNodes","key":"Casbin.Parser.TParser.getNodes","href":"Casbin.Parser.TParser.getNodes.htm"}
,{"title":"getParseType","key":"Casbin.Parser.TParser.getParseType","href":"Casbin.Parser.TParser.getParseType.htm"}
,{"title":"getStatus","key":"Casbin.Parser.TParser.getStatus","href":"Casbin.Parser.TParser.getStatus.htm"}
,{"title":"parse","key":"Casbin.Parser.TParser.parse","href":"Casbin.Parser.TParser.parse.htm"}
,{"title":"parseContent","key":"Casbin.Parser.TParser.parseContent","href":"Casbin.Parser.TParser.parseContent.htm"}
,{"title":"setLogger(ILogger)","key":"Casbin.Parser.TParser.setLogger(ILogger)","href":"Casbin.Parser.TParser.setLogger.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.TParser_Fields","href":"Casbin.Parser.TParser_Fields.htm","children":[{"title":"fErrorMessage","key":"Casbin.Parser.TParser.fErrorMessage","href":"Casbin.Parser.TParser.fErrorMessage.htm"}
,{"title":"fLogger","key":"Casbin.Parser.TParser.fLogger","href":"Casbin.Parser.TParser.fLogger.htm"}
,{"title":"fNodes","key":"Casbin.Parser.TParser.fNodes","href":"Casbin.Parser.TParser.fNodes.htm"}
,{"title":"fParseString","key":"Casbin.Parser.TParser.fParseString","href":"Casbin.Parser.TParser.fParseString.htm"}
,{"title":"fParseType","key":"Casbin.Parser.TParser.fParseType","href":"Casbin.Parser.TParser.fParseType.htm"}
,{"title":"fStatus","key":"Casbin.Parser.TParser.fStatus","href":"Casbin.Parser.TParser.fStatus.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Parser.AST","key":"Casbin.Parser.AST","href":"Casbin.Parser.AST.htm","children":[{"title":"Routines","key":"Casbin.Parser.AST_Routines","href":"Casbin.Parser.AST_Routines.htm","children":[{"title":"addAssertion(THeaderNode,string)","key":"Casbin.Parser.AST.addAssertion(THeaderNode,string)","href":"Casbin.Parser.AST.addAssertion.htm"}
]}
]}
,{"title":"Casbin.Parser.AST.Types","key":"Casbin.Parser.AST.Types","href":"Casbin.Parser.AST.Types.htm","children":[{"title":"Classes","key":"Casbin.Parser.AST.Types_Classes","href":"Casbin.Parser.AST.Types_Classes.htm","children":[{"title":"TAssertionNode","key":"Casbin.Parser.AST.Types.TAssertionNode","href":"Casbin.Parser.AST.Types.TAssertionNode.htm","children":[{"title":"Methods","key":"Casbin.Parser.AST.Types.TAssertionNode_Methods","href":"Casbin.Parser.AST.Types.TAssertionNode_Methods.htm","children":[{"title":"toOutputString","key":"Casbin.Parser.AST.Types.TAssertionNode.toOutputString","href":"Casbin.Parser.AST.Types.TAssertionNode.toOutputString.htm"}
]}
]}
,{"title":"TBaseNode","key":"Casbin.Parser.AST.Types.TBaseNode","href":"Casbin.Parser.AST.Types.TBaseNode.htm","children":[{"title":"Properties","key":"Casbin.Parser.AST.Types.TBaseNode_Properties","href":"Casbin.Parser.AST.Types.TBaseNode_Properties.htm","children":[{"title":"Key","key":"Casbin.Parser.AST.Types.TBaseNode.Key","href":"Casbin.Parser.AST.Types.TBaseNode.Key.htm"}
,{"title":"Value","key":"Casbin.Parser.AST.Types.TBaseNode.Value","href":"Casbin.Parser.AST.Types.TBaseNode.Value.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.AST.Types.TBaseNode_Methods","href":"Casbin.Parser.AST.Types.TBaseNode_Methods.htm","children":[{"title":"toOutputString","key":"Casbin.Parser.AST.Types.TBaseNode.toOutputString","href":"Casbin.Parser.AST.Types.TBaseNode.toOutputString.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.AST.Types.TBaseNode_Fields","href":"Casbin.Parser.AST.Types.TBaseNode_Fields.htm","children":[{"title":"fKey","key":"Casbin.Parser.AST.Types.TBaseNode.fKey","href":"Casbin.Parser.AST.Types.TBaseNode.fKey.htm"}
,{"title":"fValue","key":"Casbin.Parser.AST.Types.TBaseNode.fValue","href":"Casbin.Parser.AST.Types.TBaseNode.fValue.htm"}
]}
]}
,{"title":"TChildNode","key":"Casbin.Parser.AST.Types.TChildNode","href":"Casbin.Parser.AST.Types.TChildNode.htm","children":[{"title":"Constructors","key":"Casbin.Parser.AST.Types.TChildNode_Constructors","href":"Casbin.Parser.AST.Types.TChildNode_Constructors.htm","children":[{"title":"Create","key":"Casbin.Parser.AST.Types.TChildNode.Create","href":"Casbin.Parser.AST.Types.TChildNode.Create.htm"}
,{"title":"Destroy","key":"Casbin.Parser.AST.Types.TChildNode.Destroy","href":"Casbin.Parser.AST.Types.TChildNode.Destroy.htm"}
]}
,{"title":"Properties","key":"Casbin.Parser.AST.Types.TChildNode_Properties","href":"Casbin.Parser.AST.Types.TChildNode_Properties.htm","children":[{"title":"AssertionList","key":"Casbin.Parser.AST.Types.TChildNode.AssertionList","href":"Casbin.Parser.AST.Types.TChildNode.AssertionList.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.AST.Types.TChildNode_Methods","href":"Casbin.Parser.AST.Types.TChildNode_Methods.htm","children":[{"title":"toOutputString","key":"Casbin.Parser.AST.Types.TChildNode.toOutputString","href":"Casbin.Parser.AST.Types.TChildNode.toOutputString.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.AST.Types.TChildNode_Fields","href":"Casbin.Parser.AST.Types.TChildNode_Fields.htm","children":[{"title":"fAssertionList","key":"Casbin.Parser.AST.Types.TChildNode.fAssertionList","href":"Casbin.Parser.AST.Types.TChildNode.fAssertionList.htm"}
]}
]}
,{"title":"TEffectNode","key":"Casbin.Parser.AST.Types.TEffectNode","href":"Casbin.Parser.AST.Types.TEffectNode.htm","children":[{"title":"Properties","key":"Casbin.Parser.AST.Types.TEffectNode_Properties","href":"Casbin.Parser.AST.Types.TEffectNode_Properties.htm","children":[{"title":"EffectCondition","key":"Casbin.Parser.AST.Types.TEffectNode.EffectCondition","href":"Casbin.Parser.AST.Types.TEffectNode.EffectCondition.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.AST.Types.TEffectNode_Fields","href":"Casbin.Parser.AST.Types.TEffectNode_Fields.htm","children":[{"title":"fEffectCondition","key":"Casbin.Parser.AST.Types.TEffectNode.fEffectCondition","href":"Casbin.Parser.AST.Types.TEffectNode.fEffectCondition.htm"}
]}
]}
,{"title":"THeaderNode","key":"Casbin.Parser.AST.Types.THeaderNode","href":"Casbin.Parser.AST.Types.THeaderNode.htm","children":[{"title":"Constructors","key":"Casbin.Parser.AST.Types.THeaderNode_Constructors","href":"Casbin.Parser.AST.Types.THeaderNode_Constructors.htm","children":[{"title":"Create","key":"Casbin.Parser.AST.Types.THeaderNode.Create","href":"Casbin.Parser.AST.Types.THeaderNode.Create.htm"}
,{"title":"Destroy","key":"Casbin.Parser.AST.Types.THeaderNode.Destroy","href":"Casbin.Parser.AST.Types.THeaderNode.Destroy.htm"}
]}
,{"title":"Properties","key":"Casbin.Parser.AST.Types.THeaderNode_Properties","href":"Casbin.Parser.AST.Types.THeaderNode_Properties.htm","children":[{"title":"ChildNodes","key":"Casbin.Parser.AST.Types.THeaderNode.ChildNodes","href":"Casbin.Parser.AST.Types.THeaderNode.ChildNodes.htm"}
,{"title":"SectionType","key":"Casbin.Parser.AST.Types.THeaderNode.SectionType","href":"Casbin.Parser.AST.Types.THeaderNode.SectionType.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.AST.Types.THeaderNode_Methods","href":"Casbin.Parser.AST.Types.THeaderNode_Methods.htm","children":[{"title":"toOutputString","key":"Casbin.Parser.AST.Types.THeaderNode.toOutputString","href":"Casbin.Parser.AST.Types.THeaderNode.toOutputString.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.AST.Types.THeaderNode_Fields","href":"Casbin.Parser.AST.Types.THeaderNode_Fields.htm","children":[{"title":"fSectionType","key":"Casbin.Parser.AST.Types.THeaderNode.fSectionType","href":"Casbin.Parser.AST.Types.THeaderNode.fSectionType.htm"}
,{"title":"fStatementNode","key":"Casbin.Parser.AST.Types.THeaderNode.fStatementNode","href":"Casbin.Parser.AST.Types.THeaderNode.fStatementNode.htm"}
]}
]}
,{"title":"TNodeCollection","key":"Casbin.Parser.AST.Types.TNodeCollection","href":"Casbin.Parser.AST.Types.TNodeCollection.htm","children":[{"title":"Constructors","key":"Casbin.Parser.AST.Types.TNodeCollection_Constructors","href":"Casbin.Parser.AST.Types.TNodeCollection_Constructors.htm","children":[{"title":"Create","key":"Casbin.Parser.AST.Types.TNodeCollection.Create","href":"Casbin.Parser.AST.Types.TNodeCollection.Create.htm"}
,{"title":"Destroy","key":"Casbin.Parser.AST.Types.TNodeCollection.Destroy","href":"Casbin.Parser.AST.Types.TNodeCollection.Destroy.htm"}
]}
,{"title":"Properties","key":"Casbin.Parser.AST.Types.TNodeCollection_Properties","href":"Casbin.Parser.AST.Types.TNodeCollection_Properties.htm","children":[{"title":"Headers","key":"Casbin.Parser.AST.Types.TNodeCollection.Headers","href":"Casbin.Parser.AST.Types.TNodeCollection.Headers.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.AST.Types.TNodeCollection_Methods","href":"Casbin.Parser.AST.Types.TNodeCollection_Methods.htm","children":[{"title":"toOutputString","key":"Casbin.Parser.AST.Types.TNodeCollection.toOutputString","href":"Casbin.Parser.AST.Types.TNodeCollection.toOutputString.htm"}
]}
,{"title":"Fields","key":"Casbin.Parser.AST.Types.TNodeCollection_Fields","href":"Casbin.Parser.AST.Types.TNodeCollection_Fields.htm","children":[{"title":"fHeaders","key":"Casbin.Parser.AST.Types.TNodeCollection.fHeaders","href":"Casbin.Parser.AST.Types.TNodeCollection.fHeaders.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Parser.Types","key":"Casbin.Parser.Types","href":"Casbin.Parser.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Parser.Types_Interfaces","href":"Casbin.Parser.Types_Interfaces.htm","children":[{"title":"IParser","key":"Casbin.Parser.Types.IParser","href":"Casbin.Parser.Types.IParser.htm","children":[{"title":"Properties","key":"Casbin.Parser.Types.IParser_Properties","href":"Casbin.Parser.Types.IParser_Properties.htm","children":[{"title":"ErrorMessage","key":"Casbin.Parser.Types.IParser.ErrorMessage","href":"Casbin.Parser.Types.IParser.ErrorMessage.htm"}
,{"title":"Logger","key":"Casbin.Parser.Types.IParser.Logger","href":"Casbin.Parser.Types.IParser.Logger.htm"}
,{"title":"Nodes","key":"Casbin.Parser.Types.IParser.Nodes","href":"Casbin.Parser.Types.IParser.Nodes.htm"}
,{"title":"ParseType","key":"Casbin.Parser.Types.IParser.ParseType","href":"Casbin.Parser.Types.IParser.ParseType.htm"}
,{"title":"Status","key":"Casbin.Parser.Types.IParser.Status","href":"Casbin.Parser.Types.IParser.Status.htm"}
]}
,{"title":"Methods","key":"Casbin.Parser.Types.IParser_Methods","href":"Casbin.Parser.Types.IParser_Methods.htm","children":[{"title":"getErrorMessage","key":"Casbin.Parser.Types.IParser.getErrorMessage","href":"Casbin.Parser.Types.IParser.getErrorMessage.htm"}
,{"title":"getLogger","key":"Casbin.Parser.Types.IParser.getLogger","href":"Casbin.Parser.Types.IParser.getLogger.htm"}
,{"title":"getNodes","key":"Casbin.Parser.Types.IParser.getNodes","href":"Casbin.Parser.Types.IParser.getNodes.htm"}
,{"title":"getParseType","key":"Casbin.Parser.Types.IParser.getParseType","href":"Casbin.Parser.Types.IParser.getParseType.htm"}
,{"title":"getStatus","key":"Casbin.Parser.Types.IParser.getStatus","href":"Casbin.Parser.Types.IParser.getStatus.htm"}
,{"title":"parse","key":"Casbin.Parser.Types.IParser.parse","href":"Casbin.Parser.Types.IParser.parse.htm"}
,{"title":"setLogger(ILogger)","key":"Casbin.Parser.Types.IParser.setLogger(ILogger)","href":"Casbin.Parser.Types.IParser.setLogger.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"Casbin.Parser.Types_Enumerations","href":"Casbin.Parser.Types_Enumerations.htm","children":[{"title":"TParserStatus","key":"Casbin.Parser.Types.TParserStatus","href":"Casbin.Parser.Types.TParserStatus.htm"}
,{"title":"TParseType","key":"Casbin.Parser.Types.TParseType","href":"Casbin.Parser.Types.TParseType.htm"}
]}
]}
,{"title":"Casbin.Policy","key":"Casbin.Policy","href":"Casbin.Policy.htm","children":[{"title":"Classes","key":"Casbin.Policy_Classes","href":"Casbin.Policy_Classes.htm","children":[{"title":"TPolicyManager","key":"Casbin.Policy.TPolicyManager","href":"Casbin.Policy.TPolicyManager.htm","children":[{"title":"Constructors","key":"Casbin.Policy.TPolicyManager_Constructors","href":"Casbin.Policy.TPolicyManager_Constructors.htm","children":[{"title":"Create(IPolicyAdapter)","key":"Casbin.Policy.TPolicyManager.Create(IPolicyAdapter)","href":"Casbin.Policy.TPolicyManager.Create(IPolicyAdapter).htm"}
,{"title":"Create(string)","key":"Casbin.Policy.TPolicyManager.Create(string)","href":"Casbin.Policy.TPolicyManager.Create(string).htm"}
]}
,{"title":"Methods","key":"Casbin.Policy.TPolicyManager_Methods","href":"Casbin.Policy.TPolicyManager_Methods.htm","children":[{"title":"add(string)","key":"Casbin.Policy.TPolicyManager.add(string)","href":"Casbin.Policy.TPolicyManager.add.htm"}
,{"title":"clear","key":"Casbin.Policy.TPolicyManager.clear","href":"Casbin.Policy.TPolicyManager.clear.htm"}
,{"title":"load(TFilterArray)","key":"Casbin.Policy.TPolicyManager.load(TFilterArray)","href":"Casbin.Policy.TPolicyManager.load.htm"}
,{"title":"loadPolicies","key":"Casbin.Policy.TPolicyManager.loadPolicies","href":"Casbin.Policy.TPolicyManager.loadPolicies.htm"}
,{"title":"policies","key":"Casbin.Policy.TPolicyManager.policies","href":"Casbin.Policy.TPolicyManager.policies.htm"}
,{"title":"policy(TFilterArray)","key":"Casbin.Policy.TPolicyManager.policy(TFilterArray)","href":"Casbin.Policy.TPolicyManager.policy.htm"}
,{"title":"policyExists(TFilterArray)","key":"Casbin.Policy.TPolicyManager.policyExists(TFilterArray)","href":"Casbin.Policy.TPolicyManager.policyExists.htm"}
,{"title":"remove(string)","key":"Casbin.Policy.TPolicyManager.remove(string)","href":"Casbin.Policy.TPolicyManager.remove(string).htm"}
,{"title":"remove(string,string)","key":"Casbin.Policy.TPolicyManager.remove(string,string)","href":"Casbin.Policy.TPolicyManager.remove(string,string).htm"}
,{"title":"section(Boolean)","key":"Casbin.Policy.TPolicyManager.section(Boolean)","href":"Casbin.Policy.TPolicyManager.section.htm"}
]}
,{"title":"Fields","key":"Casbin.Policy.TPolicyManager_Fields","href":"Casbin.Policy.TPolicyManager_Fields.htm","children":[{"title":"fAdapter","key":"Casbin.Policy.TPolicyManager.fAdapter","href":"Casbin.Policy.TPolicyManager.fAdapter.htm"}
,{"title":"fNodes","key":"Casbin.Policy.TPolicyManager.fNodes","href":"Casbin.Policy.TPolicyManager.fNodes.htm"}
,{"title":"fParser","key":"Casbin.Policy.TPolicyManager.fParser","href":"Casbin.Policy.TPolicyManager.fParser.htm"}
]}
]}
]}
]}
,{"title":"Casbin.Policy.Types","key":"Casbin.Policy.Types","href":"Casbin.Policy.Types.htm","children":[{"title":"Interfaces","key":"Casbin.Policy.Types_Interfaces","href":"Casbin.Policy.Types_Interfaces.htm","children":[{"title":"IPolicyManager","key":"Casbin.Policy.Types.IPolicyManager","href":"Casbin.Policy.Types.IPolicyManager.htm","children":[{"title":"Methods","key":"Casbin.Policy.Types.IPolicyManager_Methods","href":"Casbin.Policy.Types.IPolicyManager_Methods.htm","children":[{"title":"add(string)","key":"Casbin.Policy.Types.IPolicyManager.add(string)","href":"Casbin.Policy.Types.IPolicyManager.add.htm"}
,{"title":"clear","key":"Casbin.Policy.Types.IPolicyManager.clear","href":"Casbin.Policy.Types.IPolicyManager.clear.htm"}
,{"title":"load(TFilterArray)","key":"Casbin.Policy.Types.IPolicyManager.load(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.load.htm"}
,{"title":"policies","key":"Casbin.Policy.Types.IPolicyManager.policies","href":"Casbin.Policy.Types.IPolicyManager.policies.htm"}
,{"title":"policy(TFilterArray)","key":"Casbin.Policy.Types.IPolicyManager.policy(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.policy.htm"}
,{"title":"policyExists(TFilterArray)","key":"Casbin.Policy.Types.IPolicyManager.policyExists(TFilterArray)","href":"Casbin.Policy.Types.IPolicyManager.policyExists.htm"}
,{"title":"remove(string)","key":"Casbin.Policy.Types.IPolicyManager.remove(string)","href":"Casbin.Policy.Types.IPolicyManager.remove(string).htm"}
,{"title":"remove(string,string)","key":"Casbin.Policy.Types.IPolicyManager.remove(string,string)","href":"Casbin.Policy.Types.IPolicyManager.remove(string,string).htm"}
,{"title":"section(Boolean)","key":"Casbin.Policy.Types.IPolicyManager.section(Boolean)","href":"Casbin.Policy.Types.IPolicyManager.section.htm"}
]}
]}
]}
]}
,{"title":"oObjects","key":"oObjects","href":"OObjects.htm","children":[{"title":"Classes","key":"oObjects_Classes","href":"oObjects_Classes.htm","children":[{"title":"TNoOwnerCollection","key":"OObjects.TNoOwnerCollection","href":"OObjects.TNoOwnerCollection.htm","children":[{"title":"Methods","key":"OObjects.TNoOwnerCollection_Methods","href":"OObjects.TNoOwnerCollection_Methods.htm","children":[{"title":"FreeItem(Pointer)","key":"OObjects.TNoOwnerCollection.FreeItem(Pointer)","href":"OObjects.TNoOwnerCollection.FreeItem.htm"}
]}
]}
,{"title":"TOCollection","key":"OObjects.TOCollection","href":"OObjects.TOCollection.htm","children":[{"title":"Constructors","key":"OObjects.TOCollection_Constructors","href":"OObjects.TOCollection_Constructors.htm","children":[{"title":"Create(Integer)","key":"OObjects.TOCollection.Create(Integer)","href":"OObjects.TOCollection.Create.htm"}
,{"title":"Destroy","key":"OObjects.TOCollection.Destroy","href":"OObjects.TOCollection.Destroy.htm"}
]}
,{"title":"Methods","key":"OObjects.TOCollection_Methods","href":"OObjects.TOCollection_Methods.htm","children":[{"title":"AtFree(Integer)","key":"OObjects.TOCollection.AtFree(Integer)","href":"OObjects.TOCollection.AtFree.htm"}
,{"title":"DoFree(Pointer)","key":"OObjects.TOCollection.DoFree(Pointer)","href":"OObjects.TOCollection.DoFree.htm"}
,{"title":"FreeAll","key":"OObjects.TOCollection.FreeAll","href":"OObjects.TOCollection.FreeAll.htm"}
,{"title":"FreeItem(Pointer)","key":"OObjects.TOCollection.FreeItem(Pointer)","href":"OObjects.TOCollection.FreeItem.htm"}
]}
]}
,{"title":"TSortedCollection","key":"OObjects.TSortedCollection","href":"OObjects.TSortedCollection.htm","children":[{"title":"Constructors","key":"OObjects.TSortedCollection_Constructors","href":"OObjects.TSortedCollection_Constructors.htm","children":[{"title":"Create(Integer)","key":"OObjects.TSortedCollection.Create(Integer)","href":"OObjects.TSortedCollection.Create.htm"}
]}
,{"title":"Methods","key":"OObjects.TSortedCollection_Methods","href":"OObjects.TSortedCollection_Methods.htm","children":[{"title":"Add(Pointer)","key":"OObjects.TSortedCollection.Add(Pointer)","href":"OObjects.TSortedCollection.Add.htm"}
,{"title":"AddReplace(Pointer)","key":"OObjects.TSortedCollection.AddReplace(Pointer)","href":"OObjects.TSortedCollection.AddReplace.htm"}
,{"title":"Compare(Pointer,Pointer)","key":"OObjects.TSortedCollection.Compare(Pointer,Pointer)","href":"OObjects.TSortedCollection.Compare.htm"}
,{"title":"IndexOf(Pointer)","key":"OObjects.TSortedCollection.IndexOf(Pointer)","href":"OObjects.TSortedCollection.IndexOf.htm"}
,{"title":"KeyOf(Pointer)","key":"OObjects.TSortedCollection.KeyOf(Pointer)","href":"OObjects.TSortedCollection.KeyOf.htm"}
,{"title":"Search(Pointer,Integer)","key":"OObjects.TSortedCollection.Search(Pointer,Integer@)","href":"OObjects.TSortedCollection.Search.htm"}
]}
,{"title":"Fields","key":"OObjects.TSortedCollection_Fields","href":"OObjects.TSortedCollection_Fields.htm","children":[{"title":"Duplicates","key":"OObjects.TSortedCollection.Duplicates","href":"OObjects.TSortedCollection.Duplicates.htm"}
]}
]}
,{"title":"TStrCollection","key":"OObjects.TStrCollection","href":"OObjects.TStrCollection.htm","children":[{"title":"Methods","key":"OObjects.TStrCollection_Methods","href":"OObjects.TStrCollection_Methods.htm","children":[{"title":"Compare(Pointer,Pointer)","key":"OObjects.TStrCollection.Compare(Pointer,Pointer)","href":"OObjects.TStrCollection.Compare.htm"}
,{"title":"FreeItem(Pointer)","key":"OObjects.TStrCollection.FreeItem(Pointer)","href":"OObjects.TStrCollection.FreeItem.htm"}
]}
]}
]}
,{"title":"Constants","key":"oObjects_Constants","href":"oObjects_Constants.htm","children":[{"title":"MaxCollectionSize","key":"OObjects.MaxCollectionSize","href":"OObjects.MaxCollectionSize.htm"}
]}
]}
,{"title":"ParseClass","key":"ParseClass","href":"ParseClass.htm","children":[{"title":"Classes","key":"ParseClass_Classes","href":"ParseClass_Classes.htm","children":[{"title":"EParserException","key":"ParseClass.EParserException","href":"ParseClass.EParserException.htm"}
,{"title":"TBooleanConstant","key":"ParseClass.TBooleanConstant","href":"ParseClass.TBooleanConstant.htm","children":[{"title":"Methods","key":"ParseClass.TBooleanConstant_Methods","href":"ParseClass.TBooleanConstant_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TBooleanConstant.GetVarType","href":"ParseClass.TBooleanConstant.GetVarType.htm"}
]}
]}
,{"title":"TBooleanFunction","key":"ParseClass.TBooleanFunction","href":"ParseClass.TBooleanFunction.htm","children":[{"title":"Methods","key":"ParseClass.TBooleanFunction_Methods","href":"ParseClass.TBooleanFunction_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TBooleanFunction.GetVarType","href":"ParseClass.TBooleanFunction.GetVarType.htm"}
]}
]}
,{"title":"TComma","key":"ParseClass.TComma","href":"ParseClass.TComma.htm","children":[{"title":"Methods","key":"ParseClass.TComma_Methods","href":"ParseClass.TComma_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TComma.GetVarType","href":"ParseClass.TComma.GetVarType.htm"}
]}
]}
,{"title":"TConstant","key":"ParseClass.TConstant","href":"ParseClass.TConstant.htm","children":[{"title":"Constructors","key":"ParseClass.TConstant_Constructors","href":"ParseClass.TConstant_Constructors.htm","children":[{"title":"CreateAsDouble(string,string,Double)","key":"ParseClass.TConstant.CreateAsDouble(string,string,Double)","href":"ParseClass.TConstant.CreateAsDouble.htm"}
]}
,{"title":"Methods","key":"ParseClass.TConstant_Methods","href":"ParseClass.TConstant_Methods.htm","children":[{"title":"GetDescription","key":"ParseClass.TConstant.GetDescription","href":"ParseClass.TConstant.GetDescription.htm"}
]}
,{"title":"Fields","key":"ParseClass.TConstant_Fields","href":"ParseClass.TConstant_Fields.htm","children":[{"title":"FDescription","key":"ParseClass.TConstant.FDescription","href":"ParseClass.TConstant.FDescription.htm"}
]}
]}
,{"title":"TDoubleConstant","key":"ParseClass.TDoubleConstant","href":"ParseClass.TDoubleConstant.htm","children":[{"title":"Constructors","key":"ParseClass.TDoubleConstant_Constructors","href":"ParseClass.TDoubleConstant_Constructors.htm","children":[{"title":"Create(string,string)","key":"ParseClass.TDoubleConstant.Create(string,string)","href":"ParseClass.TDoubleConstant.Create.htm"}
,{"title":"CreateAsDouble(string,Double)","key":"ParseClass.TDoubleConstant.CreateAsDouble(string,Double)","href":"ParseClass.TDoubleConstant.CreateAsDouble.htm"}
]}
,{"title":"Properties","key":"ParseClass.TDoubleConstant_Properties","href":"ParseClass.TDoubleConstant_Properties.htm","children":[{"title":"Value","key":"ParseClass.TDoubleConstant.Value","href":"ParseClass.TDoubleConstant.Value.htm"}
]}
,{"title":"Methods","key":"ParseClass.TDoubleConstant_Methods","href":"ParseClass.TDoubleConstant_Methods.htm","children":[{"title":"AsPointer","key":"ParseClass.TDoubleConstant.AsPointer","href":"ParseClass.TDoubleConstant.AsPointer.htm"}
]}
,{"title":"Fields","key":"ParseClass.TDoubleConstant_Fields","href":"ParseClass.TDoubleConstant_Fields.htm","children":[{"title":"FValue","key":"ParseClass.TDoubleConstant.FValue","href":"ParseClass.TDoubleConstant.FValue.htm"}
]}
]}
,{"title":"TDoubleVariable","key":"ParseClass.TDoubleVariable","href":"ParseClass.TDoubleVariable.htm","children":[{"title":"Constructors","key":"ParseClass.TDoubleVariable_Constructors","href":"ParseClass.TDoubleVariable_Constructors.htm","children":[{"title":"Create(string,PDouble)","key":"ParseClass.TDoubleVariable.Create(string,PDouble)","href":"ParseClass.TDoubleVariable.Create.htm"}
]}
,{"title":"Methods","key":"ParseClass.TDoubleVariable_Methods","href":"ParseClass.TDoubleVariable_Methods.htm","children":[{"title":"AsPointer","key":"ParseClass.TDoubleVariable.AsPointer","href":"ParseClass.TDoubleVariable.AsPointer.htm"}
,{"title":"GetCanVary","key":"ParseClass.TDoubleVariable.GetCanVary","href":"ParseClass.TDoubleVariable.GetCanVary.htm"}
]}
,{"title":"Fields","key":"ParseClass.TDoubleVariable_Fields","href":"ParseClass.TDoubleVariable_Fields.htm","children":[{"title":"FValue","key":"ParseClass.TDoubleVariable.FValue","href":"ParseClass.TDoubleVariable.FValue.htm"}
]}
]}
,{"title":"TExprCollection","key":"ParseClass.TExprCollection","href":"ParseClass.TExprCollection.htm","children":[{"title":"Methods","key":"ParseClass.TExprCollection_Methods","href":"ParseClass.TExprCollection_Methods.htm","children":[{"title":"Check","key":"ParseClass.TExprCollection.Check","href":"ParseClass.TExprCollection.Check.htm"}
,{"title":"EraseExtraBrackets","key":"ParseClass.TExprCollection.EraseExtraBrackets","href":"ParseClass.TExprCollection.EraseExtraBrackets.htm"}
,{"title":"NextOper(Integer)","key":"ParseClass.TExprCollection.NextOper(Integer)","href":"ParseClass.TExprCollection.NextOper.htm"}
]}
]}
,{"title":"TExpressList","key":"ParseClass.TExpressList","href":"ParseClass.TExpressList.htm","children":[{"title":"Methods","key":"ParseClass.TExpressList_Methods","href":"ParseClass.TExpressList_Methods.htm","children":[{"title":"Compare(Pointer,Pointer)","key":"ParseClass.TExpressList.Compare(Pointer,Pointer)","href":"ParseClass.TExpressList.Compare.htm"}
,{"title":"KeyOf(Pointer)","key":"ParseClass.TExpressList.KeyOf(Pointer)","href":"ParseClass.TExpressList.KeyOf.htm"}
]}
]}
,{"title":"TExprWord","key":"ParseClass.TExprWord","href":"ParseClass.TExprWord.htm","children":[{"title":"Constructors","key":"ParseClass.TExprWord_Constructors","href":"ParseClass.TExprWord_Constructors.htm","children":[{"title":"Create(string,TDoubleFunc)","key":"ParseClass.TExprWord.Create(string,TDoubleFunc)","href":"ParseClass.TExprWord.Create.htm"}
]}
,{"title":"Properties","key":"ParseClass.TExprWord_Properties","href":"ParseClass.TExprWord_Properties.htm","children":[{"title":"AsString","key":"ParseClass.TExprWord.AsString","href":"ParseClass.TExprWord.AsString.htm"}
,{"title":"CanVary","key":"ParseClass.TExprWord.CanVary","href":"ParseClass.TExprWord.CanVary.htm"}
,{"title":"Description","key":"ParseClass.TExprWord.Description","href":"ParseClass.TExprWord.Description.htm"}
,{"title":"IsOper","key":"ParseClass.TExprWord.IsOper","href":"ParseClass.TExprWord.IsOper.htm"}
,{"title":"isVariable","key":"ParseClass.TExprWord.isVariable","href":"ParseClass.TExprWord.isVariable.htm"}
,{"title":"Name","key":"ParseClass.TExprWord.Name","href":"ParseClass.TExprWord.Name.htm"}
,{"title":"NFunctionArg","key":"ParseClass.TExprWord.NFunctionArg","href":"ParseClass.TExprWord.NFunctionArg.htm"}
,{"title":"VarType","key":"ParseClass.TExprWord.VarType","href":"ParseClass.TExprWord.VarType.htm"}
]}
,{"title":"Methods","key":"ParseClass.TExprWord_Methods","href":"ParseClass.TExprWord_Methods.htm","children":[{"title":"AsPointer","key":"ParseClass.TExprWord.AsPointer","href":"ParseClass.TExprWord.AsPointer.htm"}
,{"title":"GetAsString","key":"ParseClass.TExprWord.GetAsString","href":"ParseClass.TExprWord.GetAsString.htm"}
,{"title":"GetCanVary","key":"ParseClass.TExprWord.GetCanVary","href":"ParseClass.TExprWord.GetCanVary.htm"}
,{"title":"GetDescription","key":"ParseClass.TExprWord.GetDescription","href":"ParseClass.TExprWord.GetDescription.htm"}
,{"title":"GetIsOper","key":"ParseClass.TExprWord.GetIsOper","href":"ParseClass.TExprWord.GetIsOper.htm"}
,{"title":"GetIsVariable","key":"ParseClass.TExprWord.GetIsVariable","href":"ParseClass.TExprWord.GetIsVariable.htm"}
,{"title":"GetNFunctionArg","key":"ParseClass.TExprWord.GetNFunctionArg","href":"ParseClass.TExprWord.GetNFunctionArg.htm"}
,{"title":"GetVarType","key":"ParseClass.TExprWord.GetVarType","href":"ParseClass.TExprWord.GetVarType.htm"}
]}
,{"title":"Events","key":"ParseClass.TExprWord_Events","href":"ParseClass.TExprWord_Events.htm","children":[{"title":"DoubleFunc","key":"ParseClass.TExprWord.DoubleFunc","href":"ParseClass.TExprWord.DoubleFunc.htm"}
]}
,{"title":"Fields","key":"ParseClass.TExprWord_Fields","href":"ParseClass.TExprWord_Fields.htm","children":[{"title":"FDoubleFunc","key":"ParseClass.TExprWord.FDoubleFunc","href":"ParseClass.TExprWord.FDoubleFunc.htm"}
,{"title":"FName","key":"ParseClass.TExprWord.FName","href":"ParseClass.TExprWord.FName.htm"}
]}
]}
,{"title":"TFunction","key":"ParseClass.TFunction","href":"ParseClass.TFunction.htm","children":[{"title":"Constructors","key":"ParseClass.TFunction_Constructors","href":"ParseClass.TFunction_Constructors.htm","children":[{"title":"Create(string,string,TDoubleFunc,Integer)","key":"ParseClass.TFunction.Create(string,string,TDoubleFunc,Integer)","href":"ParseClass.TFunction.Create.htm"}
,{"title":"CreateOper(string,TDoubleFunc,Integer,Boolean,Integer)","key":"ParseClass.TFunction.CreateOper(string,TDoubleFunc,Integer,Boolean,Integer)","href":"ParseClass.TFunction.CreateOper.htm"}
]}
,{"title":"Properties","key":"ParseClass.TFunction_Properties","href":"ParseClass.TFunction_Properties.htm","children":[{"title":"OperPrec","key":"ParseClass.TFunction.OperPrec","href":"ParseClass.TFunction.OperPrec.htm"}
]}
,{"title":"Methods","key":"ParseClass.TFunction_Methods","href":"ParseClass.TFunction_Methods.htm","children":[{"title":"GetDescription","key":"ParseClass.TFunction.GetDescription","href":"ParseClass.TFunction.GetDescription.htm"}
,{"title":"GetIsOper","key":"ParseClass.TFunction.GetIsOper","href":"ParseClass.TFunction.GetIsOper.htm"}
,{"title":"GetNFunctionArg","key":"ParseClass.TFunction.GetNFunctionArg","href":"ParseClass.TFunction.GetNFunctionArg.htm"}
]}
,{"title":"Fields","key":"ParseClass.TFunction_Fields","href":"ParseClass.TFunction_Fields.htm","children":[{"title":"FDescription","key":"ParseClass.TFunction.FDescription","href":"ParseClass.TFunction.FDescription.htm"}
,{"title":"FIsOper","key":"ParseClass.TFunction.FIsOper","href":"ParseClass.TFunction.FIsOper.htm"}
,{"title":"FNFunctionArg","key":"ParseClass.TFunction.FNFunctionArg","href":"ParseClass.TFunction.FNFunctionArg.htm"}
,{"title":"FOperPrec","key":"ParseClass.TFunction.FOperPrec","href":"ParseClass.TFunction.FOperPrec.htm"}
]}
]}
,{"title":"TGeneratedVariable","key":"ParseClass.TGeneratedVariable","href":"ParseClass.TGeneratedVariable.htm","children":[{"title":"Constructors","key":"ParseClass.TGeneratedVariable_Constructors","href":"ParseClass.TGeneratedVariable_Constructors.htm","children":[{"title":"Create(string)","key":"ParseClass.TGeneratedVariable.Create(string)","href":"ParseClass.TGeneratedVariable.Create.htm"}
]}
,{"title":"Properties","key":"ParseClass.TGeneratedVariable_Properties","href":"ParseClass.TGeneratedVariable_Properties.htm","children":[{"title":"AsString","key":"ParseClass.TGeneratedVariable.AsString","href":"ParseClass.TGeneratedVariable.AsString.htm"}
,{"title":"VarType","key":"ParseClass.TGeneratedVariable.VarType","href":"ParseClass.TGeneratedVariable.VarType.htm"}
]}
,{"title":"Methods","key":"ParseClass.TGeneratedVariable_Methods","href":"ParseClass.TGeneratedVariable_Methods.htm","children":[{"title":"GetAsString","key":"ParseClass.TGeneratedVariable.GetAsString","href":"ParseClass.TGeneratedVariable.GetAsString.htm"}
,{"title":"GetCanVary","key":"ParseClass.TGeneratedVariable.GetCanVary","href":"ParseClass.TGeneratedVariable.GetCanVary.htm"}
,{"title":"GetVarType","key":"ParseClass.TGeneratedVariable.GetVarType","href":"ParseClass.TGeneratedVariable.GetVarType.htm"}
]}
,{"title":"Fields","key":"ParseClass.TGeneratedVariable_Fields","href":"ParseClass.TGeneratedVariable_Fields.htm","children":[{"title":"FAsString","key":"ParseClass.TGeneratedVariable.FAsString","href":"ParseClass.TGeneratedVariable.FAsString.htm"}
,{"title":"FVarType","key":"ParseClass.TGeneratedVariable.FVarType","href":"ParseClass.TGeneratedVariable.FVarType.htm"}
]}
]}
,{"title":"TLeftBracket","key":"ParseClass.TLeftBracket","href":"ParseClass.TLeftBracket.htm","children":[{"title":"Methods","key":"ParseClass.TLeftBracket_Methods","href":"ParseClass.TLeftBracket_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TLeftBracket.GetVarType","href":"ParseClass.TLeftBracket.GetVarType.htm"}
]}
]}
,{"title":"TLogicalStringOper","key":"ParseClass.TLogicalStringOper","href":"ParseClass.TLogicalStringOper.htm","children":[{"title":"Constructors","key":"ParseClass.TLogicalStringOper_Constructors","href":"ParseClass.TLogicalStringOper_Constructors.htm","children":[{"title":"Create(string,TExprWord,TExprWord)","key":"ParseClass.TLogicalStringOper.Create(string,TExprWord,TExprWord)","href":"ParseClass.TLogicalStringOper.Create.htm"}
]}
,{"title":"Methods","key":"ParseClass.TLogicalStringOper_Methods","href":"ParseClass.TLogicalStringOper_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TLogicalStringOper.GetVarType","href":"ParseClass.TLogicalStringOper.GetVarType.htm"}
]}
]}
,{"title":"TRightBracket","key":"ParseClass.TRightBracket","href":"ParseClass.TRightBracket.htm","children":[{"title":"Methods","key":"ParseClass.TRightBracket_Methods","href":"ParseClass.TRightBracket_Methods.htm","children":[{"title":"GetVarType","key":"ParseClass.TRightBracket.GetVarType","href":"ParseClass.TRightBracket.GetVarType.htm"}
]}
]}
,{"title":"TSimpleStringFunction","key":"ParseClass.TSimpleStringFunction","href":"ParseClass.TSimpleStringFunction.htm","children":[{"title":"Constructors","key":"ParseClass.TSimpleStringFunction_Constructors","href":"ParseClass.TSimpleStringFunction_Constructors.htm","children":[{"title":"Create(string,string,TStringFunc,TExprWord,TExprWord)","key":"ParseClass.TSimpleStringFunction.Create(string,string,TStringFunc,TExprWord,TExprWord)","href":"ParseClass.TSimpleStringFunction.Create.htm"}
]}
,{"title":"Methods","key":"ParseClass.TSimpleStringFunction_Methods","href":"ParseClass.TSimpleStringFunction_Methods.htm","children":[{"title":"Evaluate","key":"ParseClass.TSimpleStringFunction.Evaluate","href":"ParseClass.TSimpleStringFunction.Evaluate.htm"}
,{"title":"GetCanVary","key":"ParseClass.TSimpleStringFunction.GetCanVary","href":"ParseClass.TSimpleStringFunction.GetCanVary.htm"}
]}
,{"title":"Events","key":"ParseClass.TSimpleStringFunction_Events","href":"ParseClass.TSimpleStringFunction_Events.htm","children":[{"title":"StringFunc","key":"ParseClass.TSimpleStringFunction.StringFunc","href":"ParseClass.TSimpleStringFunction.StringFunc.htm"}
]}
,{"title":"Fields","key":"ParseClass.TSimpleStringFunction_Fields","href":"ParseClass.TSimpleStringFunction_Fields.htm","children":[{"title":"FLeftArg","key":"ParseClass.TSimpleStringFunction.FLeftArg","href":"ParseClass.TSimpleStringFunction.FLeftArg.htm"}
,{"title":"FRightArg","key":"ParseClass.TSimpleStringFunction.FRightArg","href":"ParseClass.TSimpleStringFunction.FRightArg.htm"}
,{"title":"FStringFunc","key":"ParseClass.TSimpleStringFunction.FStringFunc","href":"ParseClass.TSimpleStringFunction.FStringFunc.htm"}
]}
]}
,{"title":"TStringConstant","key":"ParseClass.TStringConstant","href":"ParseClass.TStringConstant.htm","children":[{"title":"Constructors","key":"ParseClass.TStringConstant_Constructors","href":"ParseClass.TStringConstant_Constructors.htm","children":[{"title":"Create(string)","key":"ParseClass.TStringConstant.Create(string)","href":"ParseClass.TStringConstant.Create.htm"}
]}
,{"title":"Methods","key":"ParseClass.TStringConstant_Methods","href":"ParseClass.TStringConstant_Methods.htm","children":[{"title":"GetAsString","key":"ParseClass.TStringConstant.GetAsString","href":"ParseClass.TStringConstant.GetAsString.htm"}
,{"title":"GetVarType","key":"ParseClass.TStringConstant.GetVarType","href":"ParseClass.TStringConstant.GetVarType.htm"}
]}
,{"title":"Fields","key":"ParseClass.TStringConstant_Fields","href":"ParseClass.TStringConstant_Fields.htm","children":[{"title":"FValue","key":"ParseClass.TStringConstant.FValue","href":"ParseClass.TStringConstant.FValue.htm"}
]}
]}
,{"title":"TStringVariable","key":"ParseClass.TStringVariable","href":"ParseClass.TStringVariable.htm","children":[{"title":"Constructors","key":"ParseClass.TStringVariable_Constructors","href":"ParseClass.TStringVariable_Constructors.htm","children":[{"title":"Create(string,PString)","key":"ParseClass.TStringVariable.Create(string,PString)","href":"ParseClass.TStringVariable.Create.htm"}
]}
,{"title":"Methods","key":"ParseClass.TStringVariable_Methods","href":"ParseClass.TStringVariable_Methods.htm","children":[{"title":"GetAsString","key":"ParseClass.TStringVariable.GetAsString","href":"ParseClass.TStringVariable.GetAsString.htm"}
,{"title":"GetCanVary","key":"ParseClass.TStringVariable.GetCanVary","href":"ParseClass.TStringVariable.GetCanVary.htm"}
,{"title":"GetVarType","key":"ParseClass.TStringVariable.GetVarType","href":"ParseClass.TStringVariable.GetVarType.htm"}
]}
,{"title":"Fields","key":"ParseClass.TStringVariable_Fields","href":"ParseClass.TStringVariable_Fields.htm","children":[{"title":"FValue","key":"ParseClass.TStringVariable.FValue","href":"ParseClass.TStringVariable.FValue.htm"}
]}
]}
,{"title":"TVaryingFunction","key":"ParseClass.TVaryingFunction","href":"ParseClass.TVaryingFunction.htm","children":[{"title":"Methods","key":"ParseClass.TVaryingFunction_Methods","href":"ParseClass.TVaryingFunction_Methods.htm","children":[{"title":"GetCanVary","key":"ParseClass.TVaryingFunction.GetCanVary","href":"ParseClass.TVaryingFunction.GetCanVary.htm"}
]}
]}
,{"title":"TVaryingStringFunction","key":"ParseClass.TVaryingStringFunction","href":"ParseClass.TVaryingStringFunction.htm","children":[{"title":"Methods","key":"ParseClass.TVaryingStringFunction_Methods","href":"ParseClass.TVaryingStringFunction_Methods.htm","children":[{"title":"GetCanVary","key":"ParseClass.TVaryingStringFunction.GetCanVary","href":"ParseClass.TVaryingStringFunction.GetCanVary.htm"}
]}
]}
]}
,{"title":"Records","key":"ParseClass_Records","href":"ParseClass_Records.htm","children":[{"title":"TArgsArray","key":"ParseClass.TArgsArray","href":"ParseClass.TArgsArray.htm","children":[{"title":"Fields","key":"ParseClass.TArgsArray_Fields","href":"ParseClass.TArgsArray_Fields.htm","children":[{"title":"Args","key":"ParseClass.TArgsArray.Args","href":"ParseClass.TArgsArray.Args.htm"}
,{"title":"ExprWord","key":"ParseClass.TArgsArray.ExprWord","href":"ParseClass.TArgsArray.ExprWord.htm"}
,{"title":"Res","key":"ParseClass.TArgsArray.Res","href":"ParseClass.TArgsArray.Res.htm"}
]}
]}
,{"title":"TExpressionRec","key":"ParseClass.TExpressionRec","href":"ParseClass.TExpressionRec.htm","children":[{"title":"Fields","key":"ParseClass.TExpressionRec_Fields","href":"ParseClass.TExpressionRec_Fields.htm","children":[{"title":"ArgList","key":"ParseClass.TExpressionRec.ArgList","href":"ParseClass.TExpressionRec.ArgList.htm"}
,{"title":"Args","key":"ParseClass.TExpressionRec.Args","href":"ParseClass.TExpressionRec.Args.htm"}
,{"title":"ExprWord","key":"ParseClass.TExpressionRec.ExprWord","href":"ParseClass.TExpressionRec.ExprWord.htm"}
,{"title":"Next","key":"ParseClass.TExpressionRec.Next","href":"ParseClass.TExpressionRec.Next.htm"}
,{"title":"Oper","key":"ParseClass.TExpressionRec.Oper","href":"ParseClass.TExpressionRec.Oper.htm"}
,{"title":"Res","key":"ParseClass.TExpressionRec.Res","href":"ParseClass.TExpressionRec.Res.htm"}
]}
]}
]}
,{"title":"Enumerations","key":"ParseClass_Enumerations","href":"ParseClass_Enumerations.htm","children":[{"title":"TOper","key":"ParseClass.TOper","href":"ParseClass.TOper.htm"}
,{"title":"TVarType","key":"ParseClass.TVarType","href":"ParseClass.TVarType.htm"}
]}
,{"title":"Delegates","key":"ParseClass_Delegates","href":"ParseClass_Delegates.htm","children":[{"title":"TDoubleFunc","key":"ParseClass.TDoubleFunc","href":"ParseClass.TDoubleFunc.htm"}
,{"title":"TStringFunc","key":"ParseClass.TStringFunc","href":"ParseClass.TStringFunc.htm"}
]}
,{"title":"Types","key":"ParseClass_Types","href":"ParseClass_Types.htm","children":[{"title":"PDouble","key":"ParseClass.PDouble","href":"ParseClass.PDouble.htm"}
,{"title":"PExpressionRec","key":"ParseClass.PExpressionRec","href":"ParseClass.PExpressionRec.htm"}
,{"title":"PString","key":"ParseClass.PString","href":"ParseClass.PString.htm"}
]}
,{"title":"Constants","key":"ParseClass_Constants","href":"ParseClass_Constants.htm","children":[{"title":"ListChar","key":"ParseClass.ListChar","href":"ParseClass.ListChar.htm"}
,{"title":"MaxArg","key":"ParseClass.MaxArg","href":"ParseClass.MaxArg.htm"}
,{"title":"Nan","key":"ParseClass.Nan","href":"ParseClass.Nan.htm"}
]}
,{"title":"Routines","key":"ParseClass_Routines","href":"ParseClass_Routines.htm","children":[{"title":"isNan(double)","key":"ParseClass.isNan(double)","href":"ParseClass.isNan.htm"}
,{"title":"_StrEq(string,string)","key":"ParseClass._StrEq(string,string)","href":"ParseClass._StrEq.htm"}
,{"title":"_StrGe(string,string)","key":"ParseClass._StrGe(string,string)","href":"ParseClass._StrGe.htm"}
,{"title":"_StrGt(string,string)","key":"ParseClass._StrGt(string,string)","href":"ParseClass._StrGt.htm"}
,{"title":"_StrIn(string,string)","key":"ParseClass._StrIn(string,string)","href":"ParseClass._StrIn.htm"}
,{"title":"_StringFunc(PExpressionRec)","key":"ParseClass._StringFunc(PExpressionRec)","href":"ParseClass._StringFunc.htm"}
,{"title":"_StrInt(string,string)","key":"ParseClass._StrInt(string,string)","href":"ParseClass._StrInt.htm"}
,{"title":"_Strle(string,string)","key":"ParseClass._Strle(string,string)","href":"ParseClass._Strle.htm"}
,{"title":"_Strlt(string,string)","key":"ParseClass._Strlt(string,string)","href":"ParseClass._Strlt.htm"}
,{"title":"_Strne(string,string)","key":"ParseClass._Strne(string,string)","href":"ParseClass._Strne.htm"}
,{"title":"_Variable(PExpressionRec)","key":"ParseClass._Variable(PExpressionRec)","href":"ParseClass._Variable.htm"}
]}
]}
,{"title":"ParseExpr","key":"ParseExpr","href":"ParseExpr.htm","children":[{"title":"Classes","key":"ParseExpr_Classes","href":"ParseExpr_Classes.htm","children":[{"title":"TCStyleParser","key":"ParseExpr.TCStyleParser","href":"ParseExpr.TCStyleParser.htm","children":[{"title":"Properties","key":"ParseExpr.TCStyleParser_Properties","href":"ParseExpr.TCStyleParser_Properties.htm","children":[{"title":"CStyle","key":"ParseExpr.TCStyleParser.CStyle","href":"ParseExpr.TCStyleParser.CStyle.htm"}
]}
,{"title":"Methods","key":"ParseExpr.TCStyleParser_Methods","href":"ParseExpr.TCStyleParser_Methods.htm","children":[{"title":"FillExpressList","key":"ParseExpr.TCStyleParser.FillExpressList","href":"ParseExpr.TCStyleParser.FillExpressList.htm"}
,{"title":"SetCStyle(Boolean)","key":"ParseExpr.TCStyleParser.SetCStyle(Boolean)","href":"ParseExpr.TCStyleParser.SetCStyle.htm"}
]}
,{"title":"Fields","key":"ParseExpr.TCStyleParser_Fields","href":"ParseExpr.TCStyleParser_Fields.htm","children":[{"title":"FCStyle","key":"ParseExpr.TCStyleParser.FCStyle","href":"ParseExpr.TCStyleParser.FCStyle.htm"}
]}
]}
,{"title":"TCustomExpressionParser","key":"ParseExpr.TCustomExpressionParser","href":"ParseExpr.TCustomExpressionParser.htm","children":[{"title":"Constructors","key":"ParseExpr.TCustomExpressionParser_Constructors","href":"ParseExpr.TCustomExpressionParser_Constructors.htm","children":[{"title":"Create","key":"ParseExpr.TCustomExpressionParser.Create","href":"ParseExpr.TCustomExpressionParser.Create.htm"}
,{"title":"Destroy","key":"ParseExpr.TCustomExpressionParser.Destroy","href":"ParseExpr.TCustomExpressionParser.Destroy.htm"}
]}
,{"title":"Properties","key":"ParseExpr.TCustomExpressionParser_Properties","href":"ParseExpr.TCustomExpressionParser_Properties.htm","children":[{"title":"ArgSeparator","key":"ParseExpr.TCustomExpressionParser.ArgSeparator","href":"ParseExpr.TCustomExpressionParser.ArgSeparator.htm"}
,{"title":"DecimSeparator","key":"ParseExpr.TCustomExpressionParser.DecimSeparator","href":"ParseExpr.TCustomExpressionParser.DecimSeparator.htm"}
,{"title":"HexChar","key":"ParseExpr.TCustomExpressionParser.HexChar","href":"ParseExpr.TCustomExpressionParser.HexChar.htm"}
,{"title":"Optimize","key":"ParseExpr.TCustomExpressionParser.Optimize","href":"ParseExpr.TCustomExpressionParser.Optimize.htm"}
]}
,{"title":"Methods","key":"ParseExpr.TCustomExpressionParser_Methods","href":"ParseExpr.TCustomExpressionParser_Methods.htm","children":[{"title":"AddExpression(string)","key":"ParseExpr.TCustomExpressionParser.AddExpression(string)","href":"ParseExpr.TCustomExpressionParser.AddExpression.htm"}
,{"title":"AddReplaceExprWord(TExprWord)","key":"ParseExpr.TCustomExpressionParser.AddReplaceExprWord(TExprWord)","href":"ParseExpr.TCustomExpressionParser.AddReplaceExprWord.htm"}
,{"title":"Check(TExprCollection)","key":"ParseExpr.TCustomExpressionParser.Check(TExprCollection)","href":"ParseExpr.TCustomExpressionParser.Check.htm"}
,{"title":"CheckArguments(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.CheckArguments(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.CheckArguments.htm"}
,{"title":"ClearExpressions","key":"ParseExpr.TCustomExpressionParser.ClearExpressions","href":"ParseExpr.TCustomExpressionParser.ClearExpressions.htm"}
,{"title":"CompileExpression(string)","key":"ParseExpr.TCustomExpressionParser.CompileExpression(string)","href":"ParseExpr.TCustomExpressionParser.CompileExpression.htm"}
,{"title":"CurrentExpression","key":"ParseExpr.TCustomExpressionParser.CurrentExpression","href":"ParseExpr.TCustomExpressionParser.CurrentExpression.htm"}
,{"title":"DefineFunction(string,string,TDoubleFunc,Integer)","key":"ParseExpr.TCustomExpressionParser.DefineFunction(string,string,TDoubleFunc,Integer)","href":"ParseExpr.TCustomExpressionParser.DefineFunction.htm"}
,{"title":"DefineStringFunction(string,string,TStringFunc)","key":"ParseExpr.TCustomExpressionParser.DefineStringFunction(string,string,TStringFunc)","href":"ParseExpr.TCustomExpressionParser.DefineStringFunction.htm"}
,{"title":"DefineStringVariable(string,PString)","key":"ParseExpr.TCustomExpressionParser.DefineStringVariable(string,PString)","href":"ParseExpr.TCustomExpressionParser.DefineStringVariable.htm"}
,{"title":"DefineVariable(string,PDouble)","key":"ParseExpr.TCustomExpressionParser.DefineVariable(string,PDouble)","href":"ParseExpr.TCustomExpressionParser.DefineVariable.htm"}
,{"title":"DisposeList(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.DisposeList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.DisposeList.htm"}
,{"title":"DisposeTree(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.DisposeTree(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.DisposeTree.htm"}
,{"title":"Evaluate(string)","key":"ParseExpr.TCustomExpressionParser.Evaluate(string)","href":"ParseExpr.TCustomExpressionParser.Evaluate.htm"}
,{"title":"EvaluateCurrent","key":"ParseExpr.TCustomExpressionParser.EvaluateCurrent","href":"ParseExpr.TCustomExpressionParser.EvaluateCurrent.htm"}
,{"title":"EvaluateDisposeTree(PExpressionRec,Boolean)","key":"ParseExpr.TCustomExpressionParser.EvaluateDisposeTree(PExpressionRec,Boolean@)","href":"ParseExpr.TCustomExpressionParser.EvaluateDisposeTree.htm"}
,{"title":"EvaluateList(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.EvaluateList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.EvaluateList.htm"}
,{"title":"FillExpressList","key":"ParseExpr.TCustomExpressionParser.FillExpressList","href":"ParseExpr.TCustomExpressionParser.FillExpressList.htm"}
,{"title":"GetFunctionDescription(string)","key":"ParseExpr.TCustomExpressionParser.GetFunctionDescription(string)","href":"ParseExpr.TCustomExpressionParser.GetFunctionDescription.htm"}
,{"title":"GetFunctionNames(TStrings)","key":"ParseExpr.TCustomExpressionParser.GetFunctionNames(TStrings)","href":"ParseExpr.TCustomExpressionParser.GetFunctionNames.htm"}
,{"title":"GetGeneratedVars(TList)","key":"ParseExpr.TCustomExpressionParser.GetGeneratedVars(TList)","href":"ParseExpr.TCustomExpressionParser.GetGeneratedVars.htm"}
,{"title":"isBoolean","key":"ParseExpr.TCustomExpressionParser.isBoolean","href":"ParseExpr.TCustomExpressionParser.isBoolean.htm"}
,{"title":"MakeLinkedList(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.MakeLinkedList(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.MakeLinkedList.htm"}
,{"title":"MakeRec","key":"ParseExpr.TCustomExpressionParser.MakeRec","href":"ParseExpr.TCustomExpressionParser.MakeRec.htm"}
,{"title":"MakeTree(TExprCollection)","key":"ParseExpr.TCustomExpressionParser.MakeTree(TExprCollection@)","href":"ParseExpr.TCustomExpressionParser.MakeTree.htm"}
,{"title":"ParseString(string)","key":"ParseExpr.TCustomExpressionParser.ParseString(string)","href":"ParseExpr.TCustomExpressionParser.ParseString.htm"}
,{"title":"RemoveConstants(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.RemoveConstants(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.RemoveConstants.htm"}
,{"title":"ReplaceExprWord(TExprWord,TExprWord)","key":"ParseExpr.TCustomExpressionParser.ReplaceExprWord(TExprWord,TExprWord)","href":"ParseExpr.TCustomExpressionParser.ReplaceExprWord.htm"}
,{"title":"ReplaceFunction(string,TObject)","key":"ParseExpr.TCustomExpressionParser.ReplaceFunction(string,TObject)","href":"ParseExpr.TCustomExpressionParser.ReplaceFunction.htm"}
,{"title":"ResultCanVary(PExpressionRec)","key":"ParseExpr.TCustomExpressionParser.ResultCanVary(PExpressionRec)","href":"ParseExpr.TCustomExpressionParser.ResultCanVary.htm"}
,{"title":"SetArgSeparator(Char)","key":"ParseExpr.TCustomExpressionParser.SetArgSeparator(Char)","href":"ParseExpr.TCustomExpressionParser.SetArgSeparator.htm"}
,{"title":"SetDecimSeparator(Char)","key":"ParseExpr.TCustomExpressionParser.SetDecimSeparator(Char)","href":"ParseExpr.TCustomExpressionParser.SetDecimSeparator.htm"}
]}
,{"title":"Fields","key":"ParseExpr.TCustomExpressionParser_Fields","href":"ParseExpr.TCustomExpressionParser_Fields.htm","children":[{"title":"ConstantsList","key":"ParseExpr.TCustomExpressionParser.ConstantsList","href":"ParseExpr.TCustomExpressionParser.ConstantsList.htm"}
,{"title":"CurrentRec","key":"ParseExpr.TCustomExpressionParser.CurrentRec","href":"ParseExpr.TCustomExpressionParser.CurrentRec.htm"}
,{"title":"FArgSeparator","key":"ParseExpr.TCustomExpressionParser.FArgSeparator","href":"ParseExpr.TCustomExpressionParser.FArgSeparator.htm"}
,{"title":"FDecimSeparator","key":"ParseExpr.TCustomExpressionParser.FDecimSeparator","href":"ParseExpr.TCustomExpressionParser.FDecimSeparator.htm"}
,{"title":"FHexChar","key":"ParseExpr.TCustomExpressionParser.FHexChar","href":"ParseExpr.TCustomExpressionParser.FHexChar.htm"}
,{"title":"FOptimize","key":"ParseExpr.TCustomExpressionParser.FOptimize","href":"ParseExpr.TCustomExpressionParser.FOptimize.htm"}
,{"title":"LastRec","key":"ParseExpr.TCustomExpressionParser.LastRec","href":"ParseExpr.TCustomExpressionParser.LastRec.htm"}
,{"title":"WordsList","key":"ParseExpr.TCustomExpressionParser.WordsList","href":"ParseExpr.TCustomExpressionParser.WordsList.htm"}
]}
]}
,{"title":"TExpressionParser","key":"ParseExpr.TExpressionParser","href":"ParseExpr.TExpressionParser.htm","children":[{"title":"Constructors","key":"ParseExpr.TExpressionParser_Constructors","href":"ParseExpr.TExpressionParser_Constructors.htm","children":[{"title":"Create","key":"ParseExpr.TExpressionParser.Create","href":"ParseExpr.TExpressionParser.Create.htm"}
,{"title":"Destroy","key":"ParseExpr.TExpressionParser.Destroy","href":"ParseExpr.TExpressionParser.Destroy.htm"}
]}
,{"title":"Properties","key":"ParseExpr.TExpressionParser_Properties","href":"ParseExpr.TExpressionParser_Properties.htm","children":[{"title":"AsBoolean[Integer]","key":"ParseExpr.TExpressionParser.AsBoolean(Integer)","href":"ParseExpr.TExpressionParser.AsBoolean[Integer].htm"}
,{"title":"AsFloat[Integer]","key":"ParseExpr.TExpressionParser.AsFloat(Integer)","href":"ParseExpr.TExpressionParser.AsFloat[Integer].htm"}
,{"title":"AsHexadecimal[Integer]","key":"ParseExpr.TExpressionParser.AsHexadecimal(Integer)","href":"ParseExpr.TExpressionParser.AsHexadecimal[Integer].htm"}
,{"title":"AsString[Integer]","key":"ParseExpr.TExpressionParser.AsString(Integer)","href":"ParseExpr.TExpressionParser.AsString[Integer].htm"}
,{"title":"CurrentIndex","key":"ParseExpr.TExpressionParser.CurrentIndex","href":"ParseExpr.TExpressionParser.CurrentIndex.htm"}
,{"title":"ExpressionSize[Integer]","key":"ParseExpr.TExpressionParser.ExpressionSize(Integer)","href":"ParseExpr.TExpressionParser.ExpressionSize[Integer].htm"}
,{"title":"Expression[Integer]","key":"ParseExpr.TExpressionParser.Expression(Integer)","href":"ParseExpr.TExpressionParser.Expression[Integer].htm"}
]}
,{"title":"Methods","key":"ParseExpr.TExpressionParser_Methods","href":"ParseExpr.TExpressionParser_Methods.htm","children":[{"title":"AddExpression(string)","key":"ParseExpr.TExpressionParser.AddExpression(string)","href":"ParseExpr.TExpressionParser.AddExpression.htm"}
,{"title":"ClearExpressions","key":"ParseExpr.TExpressionParser.ClearExpressions","href":"ParseExpr.TExpressionParser.ClearExpressions.htm"}
,{"title":"CurrentExpression","key":"ParseExpr.TExpressionParser.CurrentExpression","href":"ParseExpr.TExpressionParser.CurrentExpression.htm"}
,{"title":"FillExpressList","key":"ParseExpr.TExpressionParser.FillExpressList","href":"ParseExpr.TExpressionParser.FillExpressList.htm"}
,{"title":"GetAsBoolean(Integer)","key":"ParseExpr.TExpressionParser.GetAsBoolean(Integer)","href":"ParseExpr.TExpressionParser.GetAsBoolean.htm"}
,{"title":"GetAsHexadecimal(Integer)","key":"ParseExpr.TExpressionParser.GetAsHexadecimal(Integer)","href":"ParseExpr.TExpressionParser.GetAsHexadecimal.htm"}
,{"title":"GetAsString(Integer)","key":"ParseExpr.TExpressionParser.GetAsString(Integer)","href":"ParseExpr.TExpressionParser.GetAsString.htm"}
,{"title":"GetExpression(Integer)","key":"ParseExpr.TExpressionParser.GetExpression(Integer)","href":"ParseExpr.TExpressionParser.GetExpression.htm"}
,{"title":"GetExprSize(Integer)","key":"ParseExpr.TExpressionParser.GetExprSize(Integer)","href":"ParseExpr.TExpressionParser.GetExprSize.htm"}
,{"title":"GetResults(Integer)","key":"ParseExpr.TExpressionParser.GetResults(Integer)","href":"ParseExpr.TExpressionParser.GetResults.htm"}
,{"title":"ReplaceExprWord(TExprWord,TExprWord)","key":"ParseExpr.TExpressionParser.ReplaceExprWord(TExprWord,TExprWord)","href":"ParseExpr.TExpressionParser.ReplaceExprWord.htm"}
]}
,{"title":"Fields","key":"ParseExpr.TExpressionParser_Fields","href":"ParseExpr.TExpressionParser_Fields.htm","children":[{"title":"Expressions","key":"ParseExpr.TExpressionParser.Expressions","href":"ParseExpr.TExpressionParser.Expressions.htm"}
,{"title":"FCurrentIndex","key":"ParseExpr.TExpressionParser.FCurrentIndex","href":"ParseExpr.TExpressionParser.FCurrentIndex.htm"}
]}
]}
]}
,{"title":"Constants","key":"ParseExpr_Constants","href":"ParseExpr_Constants.htm","children":[{"title":"errorPrefix","key":"ParseExpr.errorPrefix","href":"ParseExpr.errorPrefix.htm"}
]}
,{"title":"Routines","key":"ParseExpr_Routines","href":"ParseExpr_Routines.htm","children":[{"title":"_Abs(PExpressionRec)","key":"ParseExpr._Abs(PExpressionRec)","href":"ParseExpr._Abs.htm"}
,{"title":"_Add(PExpressionRec)","key":"ParseExpr._Add(PExpressionRec)","href":"ParseExpr._Add.htm"}
,{"title":"_Add1(PExpressionRec)","key":"ParseExpr._Add1(PExpressionRec)","href":"ParseExpr._Add1.htm"}
,{"title":"_And(PExpressionRec)","key":"ParseExpr._And(PExpressionRec)","href":"ParseExpr._And.htm"}
,{"title":"_ArcCos(PExpressionRec)","key":"ParseExpr._ArcCos(PExpressionRec)","href":"ParseExpr._ArcCos.htm"}
,{"title":"_ArcCosh(PExpressionRec)","key":"ParseExpr._ArcCosh(PExpressionRec)","href":"ParseExpr._ArcCosh.htm"}
,{"title":"_ArcSin(PExpressionRec)","key":"ParseExpr._ArcSin(PExpressionRec)","href":"ParseExpr._ArcSin.htm"}
,{"title":"_ArcSinh(PExpressionRec)","key":"ParseExpr._ArcSinh(PExpressionRec)","href":"ParseExpr._ArcSinh.htm"}
,{"title":"_arctan(PExpressionRec)","key":"ParseExpr._arctan(PExpressionRec)","href":"ParseExpr._arctan.htm"}
,{"title":"_ArcTan2(PExpressionRec)","key":"ParseExpr._ArcTan2(PExpressionRec)","href":"ParseExpr._ArcTan2.htm"}
,{"title":"_ArcTanh(PExpressionRec)","key":"ParseExpr._ArcTanh(PExpressionRec)","href":"ParseExpr._ArcTanh.htm"}
,{"title":"_Assign(PExpressionRec)","key":"ParseExpr._Assign(PExpressionRec)","href":"ParseExpr._Assign.htm"}
,{"title":"_Cos(PExpressionRec)","key":"ParseExpr._Cos(PExpressionRec)","href":"ParseExpr._Cos.htm"}
,{"title":"_Cosh(PExpressionRec)","key":"ParseExpr._Cosh(PExpressionRec)","href":"ParseExpr._Cosh.htm"}
,{"title":"_DegToRad(PExpressionRec)","key":"ParseExpr._DegToRad(PExpressionRec)","href":"ParseExpr._DegToRad.htm"}
,{"title":"_Div(PExpressionRec)","key":"ParseExpr._Div(PExpressionRec)","href":"ParseExpr._Div.htm"}
,{"title":"_eq(PExpressionRec)","key":"ParseExpr._eq(PExpressionRec)","href":"ParseExpr._eq.htm"}
,{"title":"_exp(PExpressionRec)","key":"ParseExpr._exp(PExpressionRec)","href":"ParseExpr._exp.htm"}
,{"title":"_factorial(PExpressionRec)","key":"ParseExpr._factorial(PExpressionRec)","href":"ParseExpr._factorial.htm"}
,{"title":"_ge(PExpressionRec)","key":"ParseExpr._ge(PExpressionRec)","href":"ParseExpr._ge.htm"}
,{"title":"_gt(PExpressionRec)","key":"ParseExpr._gt(PExpressionRec)","href":"ParseExpr._gt.htm"}
,{"title":"_if(PExpressionRec)","key":"ParseExpr._if(PExpressionRec)","href":"ParseExpr._if.htm"}
,{"title":"_IntPower(PExpressionRec)","key":"ParseExpr._IntPower(PExpressionRec)","href":"ParseExpr._IntPower.htm"}
,{"title":"_isNaN(PExpressionRec)","key":"ParseExpr._isNaN(PExpressionRec)","href":"ParseExpr._isNaN.htm"}
,{"title":"_le(PExpressionRec)","key":"ParseExpr._le(PExpressionRec)","href":"ParseExpr._le.htm"}
,{"title":"_ln(PExpressionRec)","key":"ParseExpr._ln(PExpressionRec)","href":"ParseExpr._ln.htm"}
,{"title":"_log10(PExpressionRec)","key":"ParseExpr._log10(PExpressionRec)","href":"ParseExpr._log10.htm"}
,{"title":"_logN(PExpressionRec)","key":"ParseExpr._logN(PExpressionRec)","href":"ParseExpr._logN.htm"}
,{"title":"_lt(PExpressionRec)","key":"ParseExpr._lt(PExpressionRec)","href":"ParseExpr._lt.htm"}
,{"title":"_max(PExpressionRec)","key":"ParseExpr._max(PExpressionRec)","href":"ParseExpr._max.htm"}
,{"title":"_min(PExpressionRec)","key":"ParseExpr._min(PExpressionRec)","href":"ParseExpr._min.htm"}
,{"title":"_minus(PExpressionRec)","key":"ParseExpr._minus(PExpressionRec)","href":"ParseExpr._minus.htm"}
,{"title":"_minus1(PExpressionRec)","key":"ParseExpr._minus1(PExpressionRec)","href":"ParseExpr._minus1.htm"}
,{"title":"_mod(PExpressionRec)","key":"ParseExpr._mod(PExpressionRec)","href":"ParseExpr._mod.htm"}
,{"title":"_mult(PExpressionRec)","key":"ParseExpr._mult(PExpressionRec)","href":"ParseExpr._mult.htm"}
,{"title":"_ne(PExpressionRec)","key":"ParseExpr._ne(PExpressionRec)","href":"ParseExpr._ne.htm"}
,{"title":"_negate(PExpressionRec)","key":"ParseExpr._negate(PExpressionRec)","href":"ParseExpr._negate.htm"}
,{"title":"_not(PExpressionRec)","key":"ParseExpr._not(PExpressionRec)","href":"ParseExpr._not.htm"}
,{"title":"_or(PExpressionRec)","key":"ParseExpr._or(PExpressionRec)","href":"ParseExpr._or.htm"}
,{"title":"_Percentage(PExpressionRec)","key":"ParseExpr._Percentage(PExpressionRec)","href":"ParseExpr._Percentage.htm"}
,{"title":"_plus(PExpressionRec)","key":"ParseExpr._plus(PExpressionRec)","href":"ParseExpr._plus.htm"}
,{"title":"_Pos(string,string)","key":"ParseExpr._Pos(string,string)","href":"ParseExpr._Pos.htm"}
,{"title":"_Power(PExpressionRec)","key":"ParseExpr._Power(PExpressionRec)","href":"ParseExpr._Power.htm"}
,{"title":"_RadToDeg(PExpressionRec)","key":"ParseExpr._RadToDeg(PExpressionRec)","href":"ParseExpr._RadToDeg.htm"}
,{"title":"_randG(PExpressionRec)","key":"ParseExpr._randG(PExpressionRec)","href":"ParseExpr._randG.htm"}
,{"title":"_random(PExpressionRec)","key":"ParseExpr._random(PExpressionRec)","href":"ParseExpr._random.htm"}
,{"title":"_realDivide(PExpressionRec)","key":"ParseExpr._realDivide(PExpressionRec)","href":"ParseExpr._realDivide.htm"}
,{"title":"_round(PExpressionRec)","key":"ParseExpr._round(PExpressionRec)","href":"ParseExpr._round.htm"}
,{"title":"_sin(PExpressionRec)","key":"ParseExpr._sin(PExpressionRec)","href":"ParseExpr._sin.htm"}
,{"title":"_Sinh(PExpressionRec)","key":"ParseExpr._Sinh(PExpressionRec)","href":"ParseExpr._Sinh.htm"}
,{"title":"_sqr(PExpressionRec)","key":"ParseExpr._sqr(PExpressionRec)","href":"ParseExpr._sqr.htm"}
,{"title":"_sqrt(PExpressionRec)","key":"ParseExpr._sqrt(PExpressionRec)","href":"ParseExpr._sqrt.htm"}
,{"title":"_tan(PExpressionRec)","key":"ParseExpr._tan(PExpressionRec)","href":"ParseExpr._tan.htm"}
,{"title":"_tanh(PExpressionRec)","key":"ParseExpr._tanh(PExpressionRec)","href":"ParseExpr._tanh.htm"}
,{"title":"_trunc(PExpressionRec)","key":"ParseExpr._trunc(PExpressionRec)","href":"ParseExpr._trunc.htm"}
,{"title":"_xor(PExpressionRec)","key":"ParseExpr._xor(PExpressionRec)","href":"ParseExpr._xor.htm"}
]}
]}
]}
]